loaded_h_0(function(_){var window=this;
_.b3p=_.y("tokonb",[]);
_.sLk=_.y("GvcUpe",[_.u3a]);
_.hbk=_.y("EDPXZb",[_.u3a]);
_.OJj=_.y("pWObQe",[_.u3a]);
_.TAj=_.y("QHMAaf",[_.u3a]);
_.OYh=_.y("hBCH7c",[_.Qr]);
_.gGe=_.y("k0SRie",[]);
_.fGe=_.y("Sfc5C",[]);
_.v("mGCtob");
var cmE={[28]:_.bIr,[1]:_.OYh,[3]:_.I1h,[4]:_.f4a,[5]:_.fGe,[19]:_.gGe,[17]:_.Lxr,[6]:_.w3a,[9]:_.hbk,[11]:_.OJj,[13]:_.v3a,[15]:_.TAj,[22]:_.sLk,[27]:_.XYr,[29]:_.Bwr,[7]:_.msr,[44]:_.Mxr,[8]:_.b3p,[10]:_.YRr,[12]:_.Jxr,[16]:_.I3a,[18]:_.zUr,[20]:_.twr,[21]:_.Cwr,[41]:_.iQq,[23]:_.Yrr,[25]:_.rTq,[26]:_.uxr,[30]:_.osr,[31]:_.Kxr,[32]:_.HTr,[34]:_.tvr,[35]:_.OSr,[36]:_.nBr,[37]:_.byr,[38]:_.itr,[39]:_.VQr,[40]:_.LSr,[42]:_.Ewr,[43]:_.imr},dmE=[5,19];_.fg(_.O3a,class extends _.Jo{lLc(a){return cmE[a]}bRc(a){return dmE.includes(a)}});
_.x();
_.v("Snahre");
_.T1D=new _.Zf(_.Q3a);
_.x();
var xQd;_.yQd=function(a){var b=new xQd;return _.ai(b,1,a)};xQd=class extends _.m{constructor(a){super(a)}};_.zQd=[0,_.I,_.G,[0,_.C,_.I]];_.AQd=_.Lb(xQd,_.zQd);
_.I1D=class extends _.m{constructor(a){super(a)}};_.J1D=function(a){var b=new _.I1D;b=_.Fi(b,1,_.P_d);return _.ai(b,2,a)};
_.v("QtOnSd");

_.x();
_.v("kNibNd");

_.x();
_.v("phtgnf");
_.G1D=document.body&&_.te(document.body);_.H1D=new Map;
_.x();
_.v("hvtMT");

_.x();
_.v("u09RR");

_.x();
_.v("HTSAKd");

_.x();
_.Wiq=class extends _.m{constructor(a){super(a)}getContentPluginType(){return _.Hj(this,1)}getContent(){return _.nj(this,2)}setContent(a){return _.tk(this,2,a)}Kp(){return _.Mk(this,2)}getViewerType(){return _.Hj(this,3)}Hx(a){return _.ai(this,3,a)}getShellStyleClass(){return _.u(this,7)}getSerializedCloseConfig(){return _.nj(this,9)}};_.Xiq=[0,_.I,_.Ml,_.I,_.Sl,_.F,1,_.F,1,_.Ml,-1];_.Yiq=_.Lb(_.Wiq,_.Xiq);
_.v("yMpBcb");
var JOs,QOs,ROs,SOs,POs,MOs;JOs=function(a){return a&&typeof a==="object"&&"viewerLayers"in a&&Array.isArray(a.viewerLayers)?a.viewerLayers:null};_.LOs=function(){var a=new _.Gu(_.ZVh.Ef());return _.KOs.test(a.pathname)&&a.oa.get("sv")===void 0};_.OOs=function(a,b,c=!1){return _.La(MOs(_.NOs(a,b,c)),4)};
_.NOs=function(a,b,c=!1){var d=null;c&&a.contentPluginType===3&&(d=(0,_.T_h)(a.content));c=new _.Wiq;var e=d?_.Hj(d,4):a.contentPluginType;d=_.ai(c,1,e).setContent(d?_.nj(d,3):a.content).Hx(a.viewerType);d=_.tk(d,10,a.serializedModalityOverride);d=_.tk(d,9,a.serializedCloseConfig);a=_.eh(d,7,a.shellStyleClass);b=POs(a,b);_.lk(a,4,b);return a};
QOs=function(){var a=new _.Gu(_.ZVh.Ef()),b=a.oa.get("sv");if(!b)return null;var c=[];try{let e=(0,_.Yiq)(_.Pa(b));b=e;var d=a.searchParams.get("q");if(_.bf(b,4)===POs(b,d)||_.bf(b,4)===POs(b)){let f=_.Mk(e,9)?_.Hb(e.getSerializedCloseConfig()):void 0,g=_.Mk(e,10)?_.Hb(_.nj(e,10)):void 0;c.push({contentPluginType:e.getContentPluginType(),content:_.Hb(e.getContent()),viewerType:e.getViewerType(),serializedModalityOverride:g,serializedCloseConfig:f,shellStyleClass:e.getShellStyleClass(),entrypointId:void 0,
replacedEntrypointId:void 0,interactionVed:null,contentId:void 0,uuid:Math.random()})}}catch(e){}return c};
ROs=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{var e=a.at(-1);let g=new _.Gu(_.ZVh.Ef());e&&!_.AId?g.oa.set("sv",_.OOs(e,g.searchParams.get("q"))):g.oa.delete("sv");var f=g.toString();let h=Object.assign({},_.wg().state||{},{viewerLayers:a}),k=history.scrollRestoration;history.scrollRestoration="manual";try{b.replace?c(await d(_.zg(h,f))):c(await d(_.Kra(h,f)))}finally{c(),history.scrollRestoration=k}}finally{d()}};SOs=function(a,b=0){for(let c=0;c<a.length;++c)b=31*b+a[c]>>>0;return b};
POs=function(a,b){_.Fk(a,4)&&(a=a.clone(),a=_.df(a,4));a=MOs(a);return SOs(a,_.IHa(b||""))};MOs=_.Mb(_.Xiq);var VOs;_.KOs=RegExp("^/searchviewer/(\\w+)");_.TOs=RegExp("^/viewer/(\\w+)");_.UOs=RegExp("^/imgres");VOs=new Set([49]);
_.WOs=class extends _.Jo{static Ta(){return{service:{location:_.Hx}}}constructor(a){super();_.ZVh.Ef=()=>a.service.location.Ef()}get(){var a=JOs(_.wg().state);if(a)return{RNa:a,url:null};var b=QOs();return{RNa:a,url:b}}Fdc(a){var {RNa:b,url:c}=this.get(),d=b!==null||c!==null,e;a:{var f=(e=b!=null?b:c)!=null?e:[];try{let h=_.ZVh.Ef();if(!h||h===""){var g=!1;break a}let k=_.no(new _.ef(h),"udm");if(VOs.has(Number(k))){let l=f.at(-1);g=l&&a.getCurrentModality({modalityOverride:void 0,serializedModalityOverride:l.serializedModalityOverride})===
1?!1:!0;break a}}catch(h){}g=!1}return g?(this.update([],{replace:!0}),{layers:[],p3c:d}):c?(this.update([],{replace:!0}),c.length>0&&this.update(c,{replace:!1}),{layers:c,p3c:d}):{layers:b!=null?b:[],p3c:d}}go(a){return _.Bg(a)}update(a,b){return ROs(a,b)}addListener(a){var b=(c,d,{hasUAVisualTransition:e})=>{a(JOs(c==null?void 0:c.state)||QOs()||[],e!=null?e:!1)};_.yra(b,!0);return()=>{_.zra(b)}}};_.fg(_.V3a,_.WOs);
_.x();
_.v("y9WHyc");

_.x();
_.v("NJJMEe");

_.x();
_.v("QMVPaf");

_.x();
_.v("aBRDge");
_.r9p=class extends _.Jo{constructor(){super();this.layout=_.iDd?"A":"S"}};_.fg(_.c3a,_.r9p);
_.x();
_.v("ZNKFGf");
var B9p,C9p,D9p,E9p,F9p,G9p,H9p,I9p,K9p,L9p,M9p,J9p,N9p,O9p,P9p,S9p,T9p,U9p,V9p,W9p,X9p,Q9p,Y9p,Z9p,R9p,$9p,a$p;B9p=function(a){var b=a.window.get().visualViewport;return b?b.width:a.window.getDocument().documentElement.clientWidth};C9p=function(a){return(new URLSearchParams(a.window.getDocument().location.search)).get("gsc")==="1"};D9p=function(a){if(_.Ka.ZD()){let b,c;return(c=(b=a.window.get().visualViewport)==null?void 0:b.offsetTop)!=null?c:0}return 0};E9p=function(a,b){return b.bottom+D9p(a)};
F9p=function(a){if(_.Ka.ZD()){let b,c;return(c=(b=a.window.get().visualViewport)==null?void 0:b.offsetLeft)!=null?c:0}return 0};G9p=function(a){for(let b of a.Pb)b()};H9p=class extends _.Bd{constructor(a){super();this.window=a;this.Pb=new Set}Pa(){return Math.min(B9p(this),C9p(this)?460:_.gVh)}Da(){return C9p(this)?460:_.fVh}Ma(){var a=this.window.get().visualViewport;return B9p(this)+(a?a.offsetLeft:0)}dzc(a){this.Pb.add(a);return()=>{this.Pb.delete(a)}}};
I9p=function(a){if(_.iJd){let c;return(c=a.window.find('[data-xid="VpUvz"]').last())!=null?c:a.window.find('[data-xid="ql1BDb"]').last()}var b;return(b=a.window.find('[data-xid="VpUvz"]').first())!=null?b:a.window.find('[data-xid="ql1BDb"]').first()};K9p=function(a){var b,c=(b=document.querySelector(".nAe0Td"))!=null?b:document.querySelector('[data-xid="T0F1od"]');if(!c)return a.Oa=null;if(J9p(a)&&a.Oa)return a.Oa;b=c.getBoundingClientRect();a.Oa=b&&b.width>0?b:null;return a.Oa};
L9p=function(a){a.iA||(a.iA=new _.Ro(document.body));a.Aa||(a.Aa=new _.Ro(document.body))};M9p=function(a){var b,c=(b=a.Aa)==null?void 0:b.el();b=a.window.getDocument();c&&b.contains!==void 0&&!b.contains(c)&&(a.Aa=I9p(a)||a.Aa);if(!a.Aa)throw Error("yt");return a.Aa};J9p=function(a){if(!a.iA)throw Error("xt");a=a.iA.el().getBoundingClientRect();return a.width===0&&a.height===0};N9p=function(a,b){return a.isRtl?B9p(a)-b.left-F9p(a):b.right+F9p(a)};
O9p=class extends H9p{constructor(a,b){super(a);this.qfa=b;this.iA=a.find("#rcnt").first();this.Aa=I9p(this);this.hb=this.qfa.oa();this.hb!==0&&(a=this.qfa.Ba(c=>{this.hb=c;G9p(this)}),this.addOnDisposeCallback(a));this.iA&&this.Aa?(this.isRtl=_.te(this.iA.el()),this.Ua=this.Ba(),this.Sa=this.Ha(),this.Oa=K9p(this),this.Va=this.Eba()):(L9p(this),this.isRtl=!1,this.Sa=this.Ua=0,this.Oa=null,this.Va=0);_.Sg(this.window.getDocument().body,"XmGRxb",c=>{c=c.data.iA;c==null?(this.iA=this.window.find("#rcnt").first(),
this.Aa=this.window.find("#center_col").first()):(this.iA=new _.Ro(c.querySelector("#rcnt")),this.Aa=new _.Ro(c.querySelector("#center_col")));L9p(this)})}BKc(){var a=this.window.getDocument();return a.querySelector('[data-xid="aim-mars-input-plate"]')||a.querySelector("#aim-server-input-plate-placeholder")}La(a){var b=-Number.MAX_VALUE;for(let c of a.children().toArray())b=Math.max(b,E9p(this,c.getBoundingClientRect()));return b}Ba(){if(!J9p(this)||this.Ua===void 0){let a=0;this.Aa&&(a=N9p(this,
M9p(this).el().getBoundingClientRect()));this.Ua=a}return this.Ua}Ha(){J9p(this)&&this.Sa!==void 0||(this.Sa=N9p(this,M9p(this).el().getBoundingClientRect()));return this.Sa}Ca(){return 76}oa(){var a=K9p(this);if(a){let b=this.window.get().innerWidth;return a.width<414?b-a.right:b-a.right+20}return 8}Da(){return 486}Ea(){return 28}j6a(){var a=K9p(this);if(a){var b=this.window.get().innerHeight-a.bottom;return a.width<414?b:b+20+2}if(b=(a=(b=this.BKc())==null?void 0:b.getBoundingClientRect())&&a.width>
0&&a.height>0){b=this.isRtl?B9p(this)-a.right-F9p(this):a.left+F9p(this);let c=this.isRtl?B9p(this)-a.left-F9p(this):a.right+F9p(this),d=this.gpa(),e=d+this.pR();b=d<c+8&&e>b-8}b?(b=this.window.get().visualViewport,a=(b?b.height:this.window.getDocument().documentElement.clientHeight)-a.top+16):a=30;return a}Eba(){if(!J9p(this)||this.Va===void 0){let a=K9p(this);this.Va=a?a.width<414?a.top:a.top+20:Math.max(89+this.Ea(),this.hb)}return this.Va}gpa(){var a=this.Ma(),b=K9p(this);return b?b.width<414?
b.right-2-this.pR():b.right-20-2-this.pR():a>this.Ba()+this.Ca()+this.Da()+this.oa()?this.Ba()+this.Ca():a-this.pR()-this.oa()}pR(){var a=K9p(this);return a?a.width<414?a.width-2:Math.min(372,a.width):Math.min(Math.max(this.Ma()-this.oa(),this.Pa()),this.Da())}aNd(){return K9p(this)!==null}};P9p=function(a){a.jd=a.window.find('[jsname="IZrYQ"]').first();a.Qc=a.window.find("#B1cDYe").first();a.Dc=a.window.find('[jsname="Et4Pcb"]').first()};
S9p=function(a){Q9p(a)&&a.ob!==void 0||(a.ob=a.Oa?R9p(a,a.Oa.el().getBoundingClientRect()):null);return a.ob};T9p=function(a){var b=document.querySelector(".nAe0Td");Q9p(a)&&a.Va&&b||(a.Va=b?b.getBoundingClientRect():null);return a.Va};U9p=function(a){a.iA||(a.iA=new _.Ro(document.body));a.Aa||(a.Aa=new _.Ro(document.body))};V9p=function(a){if(!a.iA)throw Error("xt");return a.iA};W9p=function(a){if(!a.Aa)throw Error("yt");return a.Aa};
X9p=function(a){var b;return new _.No([(b=a.Zc)!=null?b:a.tcp,a.Aa,a.Oa,a.od].filter(Boolean))};Q9p=function(a){a=V9p(a).el().getBoundingClientRect();return a.width===0&&a.height===0};Y9p=function(a,b){return a.isRtl?B9p(a)-b.left-F9p(a):b.right+F9p(a)};Z9p=function(a){var b=0;a.Wb&&(b=Math.max(E9p(a,a.Wb.el().getBoundingClientRect()),b));a.Tb&&(b=Math.max(E9p(a,a.Tb.el().getBoundingClientRect()),b));return b};R9p=function(a,b){return a.isRtl?B9p(a)-b.right-F9p(a):b.left+F9p(a)};$9p=function(a){return V9p(a).hasClass("gIatYd")};
a$p=class extends H9p{constructor(a,b){super(a);this.qfa=b;this.Vb=0;this.Dc=this.Qc=this.jd=null;this.iA=a.find("#rcnt").first();this.Aa=a.find("#center_col").first();this.Wb=a.find("#searchform").first();this.Tb=a.find(".sfbg").first();this.Oa=a.find("#rhs").first();this.od=a.find('[data-xid="nmPE2b"]').first();(b=a.find(".dRpWwb").first())&&b.find('[data-vstcp*="1"]').size()>0&&(b=null);this.tcp=b;(b=a.find(".Kevs9").first())&&b.find('[data-vstcp*="1"]').size()>0&&(b=null);this.Zc=b;this.Ab=a.find(".hPcOWc").first();
this.Lc=a.find(".Fgyi2e").last();this.Nb=this.Ab!==null?a.find(".HdbW6").first():null;this.Jb=this.Ab!==null?a.find(".iNlBQe").first():null;this.Yb=a.find("#hdtb").first();this.qc=a.find("#hdtb-tls").first();this.wc=a.find("#hdtbMenus").first();a.find(".Pl4aJc").first();P9p(this);this.Cb=this.qfa.oa();this.Cb!==0&&(a=this.qfa.Ba(c=>{this.Cb=c;G9p(this)}),this.addOnDisposeCallback(a));if(this.iA){let c=_.Sg(this.iA.el(),"OkLZtd",d=>{this.Vb=d.data.e4b;G9p(this)});this.addOnDisposeCallback(()=>{_.Tg(c)})}this.iA&&
this.Aa?(this.isRtl=_.te(this.iA.el()),this.Ua=this.Ba(),this.hb=this.Ha(),this.ob=S9p(this),this.Va=T9p(this),this.wb=this.Eba()):(U9p(this),this.isRtl=!1,this.hb=this.Ua=0,this.Va=this.ob=null,this.wb=0);_.Sg(this.window.getDocument().body,"XmGRxb",c=>{c=c.data.iA;c==null?(this.iA=this.window.find("#rcnt").first(),this.Aa=this.window.find("#center_col").first(),this.Oa=this.window.find("#rhs").first()):(this.iA=new _.Ro(c.querySelector("#rcnt")),this.Aa=new _.Ro(c.querySelector("#center_col")),
this.Oa=new _.Ro(c.querySelector("#rhs")));U9p(this);this.Nb=this.Ab!==null?this.window.find(".HdbW6").first():null;this.Jb=this.Ab!==null?this.window.find(".iNlBQe").first():null;P9p(this)})}La(a){var b=-Number.MAX_VALUE;for(let c of a.children().toArray())b=Math.max(b,E9p(this,c.getBoundingClientRect()));return b}Ba(){if(!Q9p(this)||this.Ua===void 0){let a=0;_.Oo(X9p(this),b=>{var c=b.el().getBoundingClientRect(),d=Y9p(this,c);a<d&&E9p(this,c)>0&&c.height>0&&(b.children().isEmpty()||this.La(b)>
Z9p(this))&&(a=d)});Q9p(this)&&this.Ua===void 0&&a===0&&(a=B9p(this)<1100?B9p(this):1100+(B9p(this)-1100)/2);this.Ua=a}return this.Ua}Ha(){Q9p(this)&&this.hb!==void 0||(this.hb=Y9p(this,W9p(this).el().getBoundingClientRect()));return this.hb}Ca(){return $9p(this)?0:26}oa(){var a=T9p(this);if(a){let b=this.window.get().innerWidth;return a.width<414?b-a.right:b-a.right+20}return $9p(this)?20:0}Da(){return $9p(this)?784:super.Da()}Ea(){return $9p(this)?20:_.QId?28:0}j6a(){return $9p(this)?20:_.QId?16:
0}Eba(){if(!Q9p(this)||this.wb===void 0){let e=Z9p(this)+this.Ea();var a;this.Jb?a=E9p(this,this.Jb.el().getBoundingClientRect()):a=this.Nb?this.Nb.el().getBoundingClientRect().top+D9p(this):this.Lc?E9p(this,this.Lc.el().getBoundingClientRect()):this.Yb?E9p(this,this.Yb.el().getBoundingClientRect()):0;a+=this.qc&&this.qc.el().classList.contains("hdtb-tl-sel")&&this.wc?this.wc.Za().offsetHeight:0;a>0&&(a+=this.Ea());var b=0,c=[this.jd,this.Qc,this.Dc];for(d of c)d&&(c=d.el().getBoundingClientRect(),
c.height>0&&(c=E9p(this,c),!$9p(this)&&_.QId&&(c+=this.Ea()),b=Math.max(b,c)));var d=b;_.oJd&&a>e+100&&(a=0,e+=50);this.wb=(b=T9p(this))?b.width<414?b.top:b.top+20:Math.max(e,a,d,this.Ea(),this.Vb+this.Ea(),this.Cb)}return this.wb}gpa(){var a=this.Ma();if(_.yId){var b;this.Ac||(this.Ac=this.window.find('[data-container-id="rhs-col"]').first());if(b=this.Ac){var c=b.el().getBoundingClientRect();b=R9p(this,c);let d=W9p(this).el().getBoundingClientRect();c=c.left>d.right||c.right<d.left;if(b!==0&&c)return Math.min(a-
this.Pa()-this.oa(),b+8)}}return(b=T9p(this))?b.width<414?b.right-2-this.pR():b.right-20-2-this.pR():a>this.Ba()+this.Ca()+this.Da()+this.oa()?this.Ba()+this.Ca():this.Oa!==null?Math.min(a-this.Pa()-this.oa(),this.Sa()):a-this.pR()-this.oa()}Sa(){return this.Oa!==null?S9p(this):this.Ha()+this.Ca()}pR(){var a=T9p(this);return a?a.width<414?a.width-2:Math.min(372,a.width):Math.min(Math.max(this.Ma()-this.oa()-this.Sa(),this.Pa()),this.Da())}aNd(){return T9p(this)!==null}};
_.b$p=class extends _.Jo{static Ta(){return{service:{window:_.mv,qfa:_.Rx,D2a:_.r9p}}}constructor(a){super();this.Aa=this.oa=null;this.window=a.service.window;this.qfa=a.service.qfa;this.D2a=a.service.D2a}get(){if(this.D2a.layout==="A")return this.oa||(this.oa=new O9p(this.window,this.qfa)),this.oa;this.Aa||(this.Aa=new a$p(this.window,this.qfa));return this.Aa}};_.fg(_.e3a,_.b$p);
_.x();
_.v("g9xvRd");
var K1D,L1D,M1D,N1D,O1D,P1D,Q1D,R1D;K1D=function(a){var b=_.H1D.get(a);b&&(b.M1e(),_.Vn(b.fE),_.Vn(b.Pz),_.H1D.delete(a))};
L1D=function(a){if(_.QId){var b=document.getElementById("rcnt");if(b){var c=document.getElementById("svgapmsk");c||(c=document.createElement("div"),c.id="svgapmsk",c.style.position="absolute",c.style.top="1px",c.style.bottom="0",c.className="Ksi7Wb",c.style.zIndex="10",b.appendChild(c));window.getComputedStyle(b).position==="static"&&(b.style.position="relative");c.style.display="block";c.style.width=`${a.width+20}px`;a.isRtl?(c.style.right=`${a.left}px`,c.style.left="unset"):(c.style.left=`${a.left}px`,
c.style.right="unset")}}};M1D={apply(a){a.style.position="fixed";a.style.visibility="hidden";a.style.bottom="0";a.style.left="0";a.style.width="100%";a.style.height="70%"},Cab(a){a.style.position="";a.style.visibility="";a.style.bottom="";a.style.left="";a.style.width="";a.style.height=""}};
N1D={apply(a,b,c,d,e){a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";a.style.display="block";a.style.visibility=b?"hidden":"";a.style.zIndex=`${1E3+e}`},Cab(a){a.style.position="";a.style.top="";a.style.left="";a.style.width="";a.style.height="";a.style.display="";a.style.visibility="";a.style.zIndex=""}};
O1D={apply(a,b){b&&(a.style.visibility="hidden");_.gA?a.classList.add("Yktdff"):a.classList.add("MiFXAd")},Cab(a){a.style.visibility="";a.classList.remove("Yktdff");a.classList.remove("MiFXAd")}};
P1D={apply(a,b,c,d,e){_.QId&&document.body.setAttribute("data-sv-shown","1");var f=c.get();a.style.position="fixed";try{L1D({left:f.gpa(),width:f.pR(),isRtl:_.G1D})}catch(h){}a.style.top=`${f.Eba()}px`;a.style.bottom=`${f.j6a()}px`;a.style[_.G1D?"right":"left"]=`${f.gpa()}px`;a.style.width=`${f.pR()}px`;a.style.display="block";a.style.zIndex=`${127+e}`;a.classList.add("Ooz8t");f.aNd()&&a.classList.add("F6z1Rc");var g=_.Us({}).measure(h=>{h.ccb=f.Eba();h.t9c=f.j6a()}).Gc(h=>{var k=h.t9c;a.style.top=
`${h.ccb}px`;a.style.bottom=`${k}px`}).Or().build();b=_.Be(window,"scroll",g);c=f.dzc(()=>{g()});e=_.Us({}).measure(h=>{h.VIb=f.gpa();h.tSa=f.pR();h.t9c=f.j6a();h.una=a.clientHeight}).Gc(h=>{var k=h.VIb,l=h.tSa;h=h.t9c;a.style[_.G1D?"right":"left"]=`${k}px`;a.style.width=`${l}px`;a.style.bottom=`${h}px`;try{L1D({left:k,width:l,isRtl:_.G1D})}catch(n){}}).Or().build();e=_.Be(window,"resize",e);_.H1D.set(a,{Pz:b,fE:e,M1e:c});d.then(()=>{K1D(a)})},Cab(a){K1D(a);if(document.querySelectorAll(".Ooz8t").length<=
1){document.body.removeAttribute("data-sv-shown");let b=document.getElementById("svgapmsk");b&&b.remove()}a.style.display="";a.style.position="";a.style.top="";a.style.left="";a.style.width="";a.style.bottom="";a.style.right="";a.classList.remove("Ooz8t");a.classList.remove("F6z1Rc")}};
Q1D={apply(a){a.classList.add("cnmMUc");a.id="flE2Jf";var b;(b=document.getElementById("uBYdKc"))==null||b.insertAdjacentElement("beforebegin",a);_.Zg(document.body,"flrfCd")},Cab(a,b,c){if(c){var d;(d=document.getElementById("flE2Jf"))==null||d.remove();_.Zg(document.body,"MCtCI");a.id="";a.classList.remove("cnmMUc")}}};R1D=function(a){switch(a){case 2:return P1D;case 5:return Q1D;case 4:return O1D;case 3:return M1D;default:return N1D}};
_.S1D=class extends _.Jo{static Ta(){return{service:{iA:_.b$p}}}constructor(a){super();this.oa=a.service.iA}apply(a,b){var c=this.getCurrentModality(a),d=a.Lu;if(a.QR!==c){let e=!a.QR;a.QR&&R1D(a.QR).Cab(d,this.oa,!1);R1D(c).apply(d,e,this.oa,a.yK.promise,b)}return c}Cab(a){a.QR&&R1D(a.QR).Cab(a.Lu,this.oa,!0)}getCurrentModality(a){!a.modalityOverride&&a.serializedModalityOverride&&(a.modalityOverride=(0,_.AQd)(a.serializedModalityOverride));a=a.modalityOverride;var b=new _.Gu(_.ZVh.Ef());if(_.KOs.test(b.pathname)||
_.TOs.test(b.pathname)||_.UOs.test(b.pathname))return 1;a==null&&(b=_.XZd?5:2,_.lJd?(a=_.yQd(1),b=_.J1D(b),a=_.yh(a,2,_.I1D,b)):a=_.Ux?_.yQd(b):_.yQd(1));b=a;var c;a=(c=_.Hj(b,1))!=null?c:1;b=_.oh(b,_.I1D,2,_.ph());if(_.gA)return a;c=Math.min(window.innerWidth,window.innerHeight);var d=-1;for(let e of b)b=_.Ue(e,1),c>=b&&b>=d&&(d=b,a=_.Hj(e,2));return a}};_.fg(_.N3a,_.S1D);
_.x();
var a3h=class{constructor(a,b=_.e0h()){this.vda=a;this.oa=b;this.oa.Cc("uvpet","src".toString());this.oa.Cc("uvpvoct",Math.round(a).toString());this.oa.Cc("uvpbtod","0")}Xqa(a){_.f0h(this.oa,a)}Hx(a){this.oa.Cc("vtyp",a.toString())}j_a(){this.oa.start();var a=this.oa.oa.getStartTime()+_.Dh;this.oa.qA("uvpovct",Math.round(this.vda-a));_.h0h(this.oa)}k_a(){var a=this.oa;_.g0h(a);_.kp(a,"uvpcot")}mnb(){_.i0h(this.oa)}n$a(){_.j0h(this.oa)}m$a(){_.k0h(this.oa)}i_a(){_.l0h(this.oa)}j8a(){this.oa.log();
return Promise.resolve()}};_.b3h=class extends _.n0h{constructor(a){var b=_.e0h();super(new a3h(a,b),b)}};
var kAj;_.jAj=function(a,b){switch(a){case "sa":return new _.p0h;case "o":return new _.iAj;default:return b?new _.b3h(b):new _.iAj}};
kAj=class{constructor(a=_.e0h()){this.oa=a;this.oa.Cc("uvpet","o".toString());this.oa.qA("uvpovct",0);this.oa.Cc("uvpbtod","0")}Xqa(a){_.f0h(this.oa,a)}Hx(a){this.oa.Cc("vtyp",a.toString())}j_a(){this.oa.start();_.h0h(this.oa)}k_a(){var a=this.oa;_.g0h(a);_.kp(a,"uvpcot")}mnb(){_.i0h(this.oa)}n$a(){_.j0h(this.oa)}m$a(){_.k0h(this.oa)}i_a(){_.l0h(this.oa)}j8a(){this.oa.log();return Promise.resolve()}};_.iAj=class extends _.n0h{constructor(){var a=_.e0h();super(new kAj(a),a)}};
_.J$i=function(a){_.Wn(window,"attn_viewer_open",a)};_.K$i=function(){_.Wn(window,"attn_viewer_close",null)};
_.N$h=!!(_.Qi[78]>>14&1);_.O$h=!!(_.Qi[78]>>15&1);_.P$h=!!(_.Qi[78]>>16&1);_.Q$h=!!(_.Qi[78]>>17&1);_.R$h=!!(_.Qi[78]>>18&1);
_.$2h=function(a){if(_.Z2h){var b=_.so((0,_.zm.Kz)());b.Cc("atyp","csi");b.Cc("s","uvpgws").Cc("uvpvoct",Math.round(a).toString()).log();_.Z2h=!1}};_.Z2h=!0;
var i_h=function(a){return a?a.height:0},j_h=function(a){return a?(a.left?a.left.height:0)-(a.right?a.right.height:0):0},k_h=function(a){return a?a.count:0};var l_h,p_h,q_h,t_h,n_h,o_h;_.m_h=function(a){this.Ca=a||l_h;this.Aa=this.Ba=this.oa=null};l_h=function(a,b){return String(a)<String(b)?-1:String(a)>String(b)?1:0};p_h=function(a,b){var c=j_h(b);return c>1?(j_h(b.left)<0&&n_h(a,b.left),o_h(a,b)):c<-1?(j_h(b.right)>0&&o_h(a,b.right),n_h(a,b)):b};
q_h=function(a,b,c){var d=a.Ca(b,c.value),e=!1;d>0?c.right?e=q_h(a,b,c.right):(c.right=new r_h(b,c),e=!0,c==a.Aa&&(a.Aa=c.right)):d<0&&(c.left?e=q_h(a,b,c.left):(c.left=new r_h(b,c),e=!0,c==a.Ba&&(a.Ba=c.left)));e&&(c.count++,c.height=Math.max(i_h(c.left),i_h(c.right))+1,p_h(a,c));return e};_.m_h.prototype.add=function(a){return this.oa?q_h(this,a,this.oa):(this.Aa=this.Ba=this.oa=new r_h(a),!0)};
var s_h=function(a,b,c){if(!c)return{value:null,root:null};var d=a.Ca(c.value,b);if(d>0)b=s_h(a,b,c.left),c.left=b.root,b=b.value;else if(d<0)b=s_h(a,b,c.right),c.right=b.root,b=b.value;else if(b=c.value,c.left&&c.right){b=c.value;let e=c.right;t_h(a,function(f){return f.left?e=f.left:null},c.right);c.value=e.value;d=s_h(a,e.value,c.right);c.right=d.root}else{d=c.left?c.left:c.right;if(!d)return a.Aa==c&&(a.Aa=c.parent),a.Ba==c&&(a.Ba=c.parent),{value:b,root:null};a.Aa==c&&(a.Aa=d);a.Ba==c&&(a.Ba=
d);d.parent=c.parent;c=d}c.count=k_h(c.left)+k_h(c.right)+1;c.height=Math.max(i_h(c.left),i_h(c.right))+1;return{root:p_h(a,c),value:b}};_.aa=_.m_h.prototype;_.aa.remove=function(a){a=s_h(this,a,this.oa);this.oa=a.root;return a.value};_.aa.clear=function(){this.Aa=this.Ba=this.oa=null};_.aa.contains=function(a){var b=!1;t_h(this,function(c){var d=null,e=this.Ca(c.value,a);e>0?d=c.left:e<0?d=c.right:b=!0;return d});return b};
_.aa.indexOf=function(a){var b=-1,c=0;t_h(this,function(d){var e=this.Ca(d.value,a);if(e>0)return d.left;d.left&&(c+=d.left.count);if(e<0)return c++,d.right;b=c;return null});return b};_.aa.Nk=function(){return this.oa?this.oa.count:0};_.aa.getHeight=function(){return this.oa?this.oa.height:0};_.aa.ZJ=function(){var a=[];_.u_h(this,function(b){a.push(b)});return a};
_.u_h=function(a,b){if(a.oa){a=a.Ba;for(var c=a.left?a.left:a;a!=null;)if(a.left!=null&&a.left!=c&&a.right!=c)a=a.left;else{if(a.right!=c&&b(a.value))break;let d=a;a=a.right!=null&&a.right!=c?a.right:a.parent;c=d}}};t_h=function(a,b,c){for(c=c?c:a.oa;c&&c!=null;)c=b.call(a,c)};
n_h=function(a,b){b.parent&&b.parent.left==b?(b.parent.left=b.right,b.right.parent=b.parent):b.parent&&b.parent.right==b?(b.parent.right=b.right,b.right.parent=b.parent):(a.oa=b.right,a.oa.parent=null);a=b.right;b.right=b.right.left;b.right!=null&&(b.right.parent=b);a.left=b;b.parent=a;a.count=b.count;b.count-=(a.right?a.right.count:0)+1;v_h(b);v_h(a);return a};
o_h=function(a,b){b.parent&&b.parent.left==b?(b.parent.left=b.left,b.left.parent=b.parent):b.parent&&b.parent.right==b?(b.parent.right=b.left,b.left.parent=b.parent):(a.oa=b.left,a.oa.parent=null);a=b.left;b.left=b.left.right;b.left!=null&&(b.left.parent=b);a.right=b;b.parent=a;a.count=b.count;b.count-=(a.left?a.left.count:0)+1;v_h(b);v_h(a);return a};_.m_h.prototype.copy=function(a){var b=new _.m_h(this.Ca);if(!this.oa)return b;a=this.oa.copy(null,this.Ca,a);b.oa=a.root;b.Ba=a.TAd;b.Aa=a.wKd;return b};
var r_h=function(a,b){this.value=a;this.parent=b?b:null;this.count=1;this.right=this.left=null;this.height=1},v_h=function(a){a.height=Math.max(a.left?a.left.height:0,a.right?a.right.height:0)+1};r_h.prototype.copy=function(a,b,c){var d=c?c(this.value):this.value;a=new r_h(d,a);a.count=this.count;a.height=this.height;var e=d=a;this.left&&(d=this.left.copy(a,b,c),a.left=d.root,d=d.TAd);this.right&&(b=this.right.copy(a,b,c),a.right=b.root,e=b.wKd);return{root:a,TAd:d,wKd:e}};
var x_h,B_h,C_h;_.w_h=function(a){if(a=a.id)return a};x_h=function(a,b){for(let c of a)if(c.nodeType===Node.ELEMENT_NODE){c.matches('[data-sve]:not([data-nv="1"])')&&b(c);for(let d of c.querySelectorAll('[data-sve]:not([data-nv="1"])'))b(d)}};_.y_h=function(a){return a.closest("[data-viewer-group]")};_.A_h=function(a){var b=a.getAttribute("data-ssid");return b&&b.length>0?new _.z_h(void 0,_.w_h(a)||"",b):(b=_.y_h(a))?new _.z_h(b,_.w_h(a)||""):null};
B_h=function(a,b,c){c=c||a.oa;var d=c.left?c.left.count:0;return b<d?B_h(a,b,c.left):b==d?c:B_h(a,b-d-1,c.right)};C_h=function(a,b){return b<0||b>=a.Nk()?null:B_h(a,b).value};_.D_h=class extends _.m{constructor(a){super(a)}f6a(){return _.u(this,1)}};_.E_h=[0,_.F,-1,_.D];var F_h=_.Mb(_.E_h);var G_h;G_h=function(a,b){for(let c of b)x_h(c.removedNodes,d=>{a.oa.remove(d)}),x_h(c.addedNodes,d=>{a.group&&_.y_h(d)!==a.group||a.oa.add(d)})};_.H_h=function(a,b){return a.oa.indexOf(b)};
_.z_h=class{constructor(a,b,c){this.group=a;this.Ca=b;this.Ba=new MutationObserver(g=>{G_h(this,g)});this.oa=new _.m_h(_.vKa);var d,e;this.streamId=(e=(d=a==null?void 0:a.getAttribute("data-id"))!=null?d:c)!=null?e:"";var f;this.Aa=(f=a==null?void 0:a.getAttribute("data-cid"))!=null?f:this.streamId;if(a)this.Ba.observe(a,{subtree:!0,childList:!0,attributes:!1}),x_h(a.childNodes,g=>{_.y_h(g)===this.group&&this.oa.add(g)});else if(!this.scan(b))throw Error("Cp`"+this.streamId);}scan(a){if(this.group)return 0;
this.oa.clear();var b=!1,c=document.documentElement.querySelectorAll(`[data-ssid="${this.streamId}"]`);x_h(c,d=>{d.getAttribute("data-ssid")===this.streamId&&(this.oa.add(d),a&&_.w_h(d)===a&&(b=!0))});if(a&&!b)throw Error("Dp`"+a);return this.oa.Nk()}getType(){return 1}Poe(a){var b=this.Dxb(a),c={},d;c.k=(d=b.getAttribute("data-k"))!=null?d:a;this.Aa&&(c.id=this.Aa);this.streamId&&(c.vid=this.streamId);(a=_.w_h(b))&&(c.vhid=a);return c}serialize(a){var b=new _.D_h;b=_.eh(b,1,this.streamId);a=_.w_h(this.Dxb(a));
a=_.eh(b,2,a);a=_.bi(a,3,this.group===void 0);return F_h(a)}async hQb(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let e=C_h(this.oa,a);if(!e)throw Error("Ep`"+a);try{let f,g=_.bta((f=this.group)!=null?f:e),h=c(await d(g.getController(e)));return c(await d(h.lta({source:b,count:this.fea(),index:a})))}catch(f){throw c(),Error("Fp`"+a+"`"+this.streamId+"`"+(e==null?void 0:e.id)+"`"+(e==null?void 0:e.isConnected)+"`"+f);}}finally{d()}}Dxb(a){return C_h(this.oa,a)}Hdc(){var a=0;_.u_h(this.oa,b=>{if(_.w_h(b)===
this.Ca)return!0;a++;return!1});this.fea();return a}fea(){return this.oa.Nk()}GGd(){return this.oa.Ba.value}dispose(){this.Ba.disconnect()}};
var uZh,vZh,wZh,xZh,yZh,zZh,AZh,BZh;_.tZh=function(a){_.rZh(a);var b="<div"+_.X("rVGT ")+_.Y("")+_.W("")+">";var c=_.sZh(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+"</div>";a.Ea();return _.z(b)};uZh=function(){return""};vZh=function(){return""};wZh=function(){return""};xZh=function(){return!0};yZh=function(){return!1};zZh=function(a){_.rZh(a);return _.sZh(a)};AZh=function(a){_.rZh(a);var b="<div"+_.X("rVGT ")+_.Y("")+_.W("")+">";a=_.sZh(a);return _.z(b+(a+"</div>"))};
_.sZh=function(a){a.Ba(".rVGT{display:flex;justify-content:center;left:50%;position:absolute;top:18%;transform:translateX(-50%);z-index:1}");return"<g-loading-icon"+_.X(_.XS(a,!0,null,null)+"")+_.Y(_.YS(a,!0,null,null)+"")+_.W("")+">"+_.$S(a,!0,null,null)+"</g-loading-icon>"};_.rZh=function(a){a.oa(BZh)||(a.Aa(BZh,{},zZh,AZh,xZh,yZh,"",uZh,"rVGT ",vZh,"",wZh),_.ZS(a))};BZh="t-Zg8vSMWW_Oc";
_.QXh=!!(_.Qi[78]>>20&1);_.RXh=!!(_.Qi[78]>>21&1);_.SXh=!!(_.Qi[78]>>22&1);_.TXh=!!(_.Qi[78]>>23&1);_.UXh=!!(_.Qi[78]>>24&1);_.VXh=!!(_.Qi[78]>>25&1);
_.aWh=_.dJd?"26px":"46px";
_.qfh=function(a){a=a!=null?a:document.activeViewTransition;if(!a)return[];if(a.vgd)return a.vgd;var b=document.documentElement.getAnimations({subtree:!0}).filter(c=>{var d,e,f;return(f=(d=c.effect)==null?void 0:(e=d.pseudoElement)==null?void 0:e.startsWith("::view-transition"))!=null?f:!1});return a.vgd=b};
var qHd,rHd,pHd,nHd,tHd;_.mHd=function(a){var b;a=Number((b=a.trim().match(/^(\d+|\d+\.\d+)px$/))==null?void 0:b[1]);return isNaN(a)?null:a};
_.sHd=function(a,b,c,d){if(a===b)return c;d=Number(d);isNaN(d)&&(d=500);c=c.replace(/\n/g,"").replace(/\s*,\s*/g,",").replace(/\(\s*/g,"(").replace(/\s*\)/g,")").trim();if(c.startsWith("linear("))var e=nHd(c,d);else{a:{var f=oHd[c.trim().toLowerCase()];if(f)e=f;else{try{var g=c.match(/cubic-bezier\s*\(\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*\)/i);if(g){e=g.slice(1).map(Number);break a}}catch(h){}e=oHd.linear}}g=2*Math.round(d/8.3333333);d=[];for(c=0;c<=g;c++)f=c/g,d.push([pHd(f,
e[1],e[3]),pHd(f,e[0],e[2])]);e=d}a=qHd(a,b,e);return rHd(a)};qHd=function(a,b,c){return c.map(([d,e])=>[(1/(d*(b-a)+a)-1/a)/(1/b-1/a),e])};rHd=function(a){return`linear(${a.map(([b,c])=>`${b} ${100*c}%`).join(",")})`};pHd=function(a,b,c){return(1-a)*(1-a)*(1-a)*0+3*(1-a)*(1-a)*a*b+3*(1-a)*a*a*c+a*a*a};
nHd=function(a,b){a=a.match(/linear\((.*)\)/i);var c=(a?a[1].split(",").map(e=>e.trim()):["0","1"]).map(e=>{e=e.split(" ");var f=Number(e[0]),g=[[f]];e.length>=2&&g[0].push(tHd(e[1]));e.length>=3&&g.push([f,tHd(e[2])]);return g}).flatMap(e=>e);c[0][1]=0;c[c.length-1][1]=1;for(let e=0;e<c.length;e++)if(c[e].length===1){var d=e-1;a=c.findIndex((g,h)=>h>e&&g[1]!==void 0);let f=(c[a][1]-c[d][1])/(a-d);d=c[d][1];for(let g=e;g<a;g++)d+=f,c[g][1]=d}return c.map(([e,f],g)=>{var h=[[e,f]],k=c[g+1];if(!k)return h;
var l=k[1]-f;g=Math.ceil(l*b/8.3333333);l/=g;k=(k[0]-e)/g;for(let n=0;n<g-1;n++)f+=l,e+=k,h.push([e,f]);return h}).flatMap(e=>e)};tHd=function(a){var b=Number(a.split("%")[0])/100;if(isNaN(b))throw Error("yi`"+a);return b};var oHd={linear:[0,0,1,1],ease:[.25,.1,.25,1],"ease-in":[.42,0,1,1],"ease-out":[0,0,.58,1],"ease-in-out":[.42,0,.58,1]};
var tfh,ufh,wfh,xfh,yfh,sfh,Bfh,Afh,Cfh,Hfh,Gfh,Ifh,Jfh;
tfh=function(a="root",b=1,c=!1){var d=[];if(b===0)return d;var e=_.rfh(a,c);if(!e)return d;c=e.mFd;var f=e.pFd,g=e.qFd,h=e.kFd,k=e.cEd,l=e.hEd,n=e.iEd,q=e.ava,r=e.DQ,t=e.animation,A=e.keyframes,E=e.duration,H=e.effect;e=e.zQ*(b===4?1:b===5?h/q:g/n);r=b===3||b===2?r*h/q:e;a!=="sb"&&(f+h<0||l+q<0)&&t.cancel();var M=[{transform:`translate(${c}px, ${f}px) scale(${e}, ${r})`,easing:A[0].easing,transformOrigin:"top left"},{transform:`translate(${k}px, ${l}px) scale(1, 1)`,easing:A[1].easing,transformOrigin:"top left"}];
d.push(()=>{H.setKeyframes(M)});b===2&&d.push(...sfh({name:a,easing:A[0].easing,duration:E,nFd:e,oFd:r}));return d};ufh=function(){var a,b,c;return(c=(a=navigator.userAgentData)==null?void 0:(b=a.brands)==null?void 0:b.some(d=>d.brand==="Chromium"&&d.version==="137"))!=null?c:!1};
_.rfh=function(a,b=!1){if(!ufh()){var c=`::view-transition-group(${a})`;if(a=_.qfh().find(r=>{var t;return((t=r.effect)==null?void 0:t.pseudoElement)===c})){var d=a.effect,e=d.getKeyframes(),f=a.effect.getTiming().duration;if(e[1].transform==="none"){a.currentTime=f;var g=window.getComputedStyle(document.documentElement,c);var h=new DOMMatrix(g.transform);var k=_.mHd(g.width);g=_.mHd(g.height);a.currentTime=0}else h=new DOMMatrix(e[1].transform),k=_.mHd(e[1].width),g=_.mHd(e[1].height);if(k!==null&&
g!==null){var l=_.mHd(e[0].width),n=_.mHd(e[0].height);if(l!==null&&n!==null){var q=new DOMMatrix(e[0].transform);q=_.vfh(q);b&&(q=wfh(q,l,n,c));return{mFd:q.left,pFd:q.top,qFd:l,kFd:n,cEd:h.e,hEd:h.f,iEd:k,ava:g,zQ:q.zQ,DQ:q.DQ,animation:a,keyframes:e,duration:f,effect:d}}}}}};_.vfh=function(a){return{left:a.e,top:a.f,zQ:a.a,DQ:a.d}};
wfh=function(a,b,c,d){try{let e=window.getComputedStyle(document.documentElement,d).transformOrigin,{UAd:f,FRd:g}=xfh(Object.assign({},{transformOrigin:e,width:b,height:c},a));if(isNaN(g)||isNaN(f))return a;a.left+=f;a.top+=g}catch(e){}return a};xfh=function({transformOrigin:a,width:b,height:c,zQ:d,DQ:e}){a=yfh({transformOrigin:a,height:c,width:b});return a===null?{UAd:0,FRd:0}:{UAd:a.VAd*(1-d),FRd:a.GRd*(1-e)}};
yfh=function({transformOrigin:a,height:b,width:c}){var d=a.match(/(-?\d+\.?\d*)px (-?\d+\.?\d*)px/);if(d){let [,e,f]=d;return{VAd:Number(e),GRd:Number(f)}}if(a=a.match(/(-?\d+\.?\d*)% (-?\d+\.?\d*)%/)){let [,e,f]=a;return{VAd:c*Number(e)/100,GRd:b*Number(f)/100}}return null};sfh=function(a){return _.zfh(a).map(({keyframes:b,options:c})=>()=>{try{document.documentElement.animate(b,c)}catch(d){d.details={src:"spa-vt-csa",kf:JSON.stringify(b),o:JSON.stringify(c)},d.L6f=2}})};
_.zfh=function({name:a,easing:b,duration:c,nFd:d,oFd:e,transformOrigin:f="top left"}){var g=[];if(e===1)return[];var h=`::view-transition-image-pair(${a})`;b=_.sHd(e,1,b,c);c={duration:c,easing:b};g.push({keyframes:[{transformOrigin:f,transform:`scale(1, ${d/e})`},{transformOrigin:f,transform:"scale(1, 1)"}],options:Object.assign({},c,{pseudoElement:h})});a=`::view-transition-group(${a})`;f=window.getComputedStyle(document.documentElement,a).borderRadius;(f=_.mHd(f))&&g.push({keyframes:[{borderRadius:`${f/
d}px / ${f/e}px`},{borderRadius:`${f}px`}],options:Object.assign({},c,{pseudoElement:a})});return g};Bfh=function(a){return document.startViewTransition?document.startViewTransition(a):Afh(a)};Afh=function(a){a=Promise.resolve(a()).then(()=>{});return{ready:Promise.resolve(),updateCallbackDone:a,finished:a,skipTransition:()=>{}}};Cfh=function(){var a,b,c=(a=navigator.userAgentData)==null?void 0:(b=a.brands)==null?void 0:b.find(d=>d.brand==="Chromium");return c?Number(c.version)<=113:!1};
Hfh=function(a,b={}){if(Cfh())return Afh(a);for(var c of _.Dfh())c.cancel();var d=document.createElement("style");document.head.prepend(d);var e=[],f;b.groups=(f=b.groups)!=null?f:[];var g=()=>b.root?[b.root,...b.groups]:b.groups;b.root&&(b.root.viewTransitionName="root");var h;((h=b.root)==null?0:h.disable)&&_.Efh(d,":root",{viewTransitionName:"none"});b.gmd&&_.Efh(d,"::view-transition",{pointerEvents:"none"});for(f=0;f<b.groups.length;f++)h=b.groups[f],c=`spa-vt-${f}`,h.viewTransitionName=c,h.element&&
(h.element.style.viewTransitionName=c);var k=Bfh(async()=>{var l=(0,_.Wf)(),n=l();l=l(1);try{let q=g().map(r=>{var t;return(t=r.uF)==null?void 0:t.call(r)}).filter(r=>r);l(await n(Promise.all([a(),...q])));for(let r of b.groups)r.Zua===void 0&&(r.Zua=r.fRb?r.fRb():r.element),r.element&&(r.element.style.viewTransitionName=""),r.Zua&&(r.Zua.style.viewTransitionName=r.viewTransitionName)}finally{n()}});Ffh=k;k.updateCallbackDone.then(()=>{var l,n,q;b=(q=(n=(l=b).updateCallbackDone)==null?void 0:n.call(l,
b))!=null?q:b;for(let r of b.groups){let t,A;(A=(t=r).updateCallbackDone)==null||A.call(t,r)}});k.updateCallbackDone.catch(()=>{});k.ready.then(()=>{var l,n;(n=(l=b).ready)==null||n.call(l,b);for(let q of b.groups){let r,t;(t=(r=q).ready)==null||t.call(r,q)}for(let q of b.groups)q.Zua&&(q.Zua.style.viewTransitionName="");for(let q of g())e.push(...Gfh(d,q));for(let q of g()){let r;((r=q)==null?0:r.Ueb)&&e.push(...tfh(q.viewTransitionName,q.Ueb,q.ozc))}for(let q of e)q()},()=>{});k.finished.catch(()=>
{});k.finished.finally(()=>{var l,n;(n=(l=b).finished)==null||n.call(l,b);for(let q of b.groups){let r,t;(t=(r=q).finished)==null||t.call(r,q)}for(let q of b.groups)q.element&&(q.element.style.viewTransitionName=""),q.Zua&&(q.Zua.style.viewTransitionName="");Ffh===k&&(Ffh=null);d.remove()});return k};Gfh=function(a,b){if(!b)return[];var c=b.viewTransitionName;return[Ifh(a,c,"old",b.bBa),Ifh(a,c,"new",b.new),Ifh(a,c,"group",b.group),Ifh(a,c,"image-pair",b.FTb)].flatMap(d=>d)};
Ifh=function(a,b,c,d){var e=[];if(!d)return e;d.animation&&(e.push(Jfh(b,c,d.animation)),d.styles=d.styles||{},d.styles.animation="none");var f;(f=d.lzc)==null||f.forEach(g=>{e.push(Jfh(b,c,g))});d.styles&&_.Efh(a,`::view-transition-${c}(${b})`,d.styles);return e};Jfh=function(a,b,c){var d=`::view-transition-${b}(${a})`;return()=>document.documentElement.animate(c.keyframes,Object.assign({},c.options,{pseudoElement:d}))};
_.Efh=function(a,b,c){b=a.sheet.insertRule(`${b} {}`);a=a.sheet.cssRules[b];for(let d in c)c.hasOwnProperty(d)&&(a.style[d]=c[d]);return a};_.Dfh=function(){return document.getAnimations().filter(a=>{a=a.effect;var b;return(a==null?void 0:a.target)===document.documentElement&&((b=a.pseudoElement)==null?void 0:b.startsWith("::view-transition"))})};_.Lfh=function(a,b){return _.Kfh||(b==null||!b.Xve)&&window.matchMedia("(prefers-reduced-motion: reduce)").matches?Afh(a):Hfh(a,b)};_.Kfh=!!(_.Qi[75]&64);
_.Mfh=!!(_.Qi[75]&128);var Ffh;_.Nfh=!!document.startViewTransition;Ffh=null;"activeViewTransition"in document||Object.defineProperty(document,"activeViewTransition",{get(){return Ffh},configurable:!0});
_.eGe=function(a,b){b=_.Xpa({Mc:b},!1);b=_.Mf(b);try{return _.Tf(a instanceof _.Xb?_.gqa(a):a)}finally{_.Mf(b)}};
_.v("Sp69O");
var c2D,d2D,e2D,g2D,f2D,i2D,h2D,l2D,m2D,s2D,t2D,D2D,B2D,E2D,H2D,I2D,G2D,J2D,F2D,L2D,K2D,M2D,x2D,C2D,N2D,O2D,P2D,u2D,Q2D,w2D,R2D,S2D,A2D,b2D,T2D,U2D,j2D;c2D=function(a){if(b2D)return b2D;var b=_.Ve(_.Tm("iGkMSe"));return b2D=_.q0h(a,251333,b)};
d2D=function(a,b){var c={duration:250,easing:"cubic-bezier(.75,1,.75,1)"},d=b.width/a.width,e=b.left-a.left*d;a=b.top-a.top*d;return{cJe:{keyframes:[{opacity:1,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:0,transform:`translate(${e}px, ${a}px) scale(${d})`,transformOrigin:"top left",mixBlendMode:"normal"}],options:c},aIe:{keyframes:[{opacity:0,transform:`translate(${-e/d}px, ${-a/d}px) scale(${1/d})`,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:1,
transformOrigin:"top left",mixBlendMode:"normal"}],options:c}}};
e2D=function({element:a,Zua:b,fRb:c,Ueb:d=2,containment:e=!0,fBd:f,heg:g,grd:h,Gbg:k,F9f:l=.5,backgroundColor:n,ozc:q=!1,options:r={}}){var t;r.duration=(t=r.duration)!=null?t:250;var A;r.easing=(A=r.easing)!=null?A:_.LTb;var E;r.fill=(E=r.fill)!=null?E:"both";var H=r.duration,M=r.easing;b={element:a,Zua:b,fRb:c,group:{},FTb:{},bBa:{},new:{}};e&&(b.group.styles={overflow:"hidden",borderRadius:"20px",backgroundColor:n||window.getComputedStyle(document.body).backgroundColor});var P=a.getBoundingClientRect(),
R=g!=null?g:f==null?void 0:f.getBoundingClientRect();b.ready=Z=>{if(Z.Zua){var ba;Z.group=(ba=Z.group)!=null?ba:{};if(ba=_.rfh(Z.viewTransitionName,q)){var ia=ba.mFd,ha=ba.pFd,ma=ba.qFd,sa=ba.kFd,Fa=ba.cEd,Da=ba.hEd,eb=ba.iEd,Ma=ba.ava,cb=ba.zQ,nb=ba.DQ;ba=Z.Zua.getBoundingClientRect();var Ob,Jb=k?k():(Ob=h?h():f)==null?void 0:Ob.getBoundingClientRect();Ob=nb*sa/Ma;ma=d===4?1:d===5?Ob:cb*ma/eb;eb=d===3||d===2?Ob:ma;Z.group.animation={keyframes:[{transform:`translate(${ia}px, ${ha}px) scale(${ma}, ${eb})`,
transformOrigin:"top left"},{transform:`translate(${Fa}px, ${Da}px) scale(1, 1)`,transformOrigin:"top left"}],options:r};d===2&&(Z.FTb!=null||(Z.FTb={}),ia=_.zfh({name:Z.viewTransitionName,easing:M,duration:H,nFd:ma,oFd:eb}),Z.FTb.animation=ia[0],Z.FTb.lzc=ia.slice(1));R&&Jb&&Z.bBa&&Z.new&&(ia=Jb.left-ba.left-(R.left-P.left),ba=Jb.top-ba.top-(R.top-P.top),Jb={keyframes:[{offset:0,opacity:"0",transform:`translate(${-ia}px, ${-ba}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-
.1,opacity:"0"},{offset:l+.1,opacity:"1"},{offset:1,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},Z.bBa.animation={keyframes:[{offset:0,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-.1,opacity:"1"},{offset:l+.1,opacity:"0"},{offset:1,opacity:"0",transform:`translate(${ia}px, ${ba}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},Z.new.animation=Jb);
return Z}}};return b};g2D=function(a,b){b=f2D(a,b);return b!=null&&b!==0?b:f2D(a,_.Q_d)};f2D=function(a,b){switch(a){case 0:case 1:return b==null?void 0:_.Hj(b,2);case 2:return b==null?void 0:_.Hj(b,3);case 3:return b==null?void 0:_.Hj(b,4);case 4:return b==null?void 0:_.Hj(b,5);default:_.Ya(a,void 0)}};i2D=async function(a,b,c){var d=(0,_.Wf)(),e=d();d=d(1);try{let f=b.map(h2D);d(await e(a.update(f,c)))}finally{e()}};
h2D=function(a){return{contentPluginType:a.contentPluginType,content:a.content,viewerType:a.viewerType,serializedModalityOverride:a.modalityOverride?j2D(a.modalityOverride):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,entrypointId:a.entrypointId,replacedEntrypointId:a.replacedEntrypointId,interactionVed:a.interactionVed,contentId:a.contentId,uuid:a.uuid}};
l2D=function(a){return{viewerType:a.viewerType,modalityOverride:a.serializedModalityOverride?(0,_.AQd)(a.serializedModalityOverride):void 0,serializedModalityOverride:void 0,rZ:a.serializedCloseConfig?(0,_.vQd)(a.serializedCloseConfig):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,Lu:null,plugin:null,FP:new AbortController,contentPluginType:a.contentPluginType,content:a.content,entrypointId:a.entrypointId,contentId:a.contentId,replacedEntrypointId:a.replacedEntrypointId,
sjb:0,raa:new k2D,interactionVed:a.interactionVed,Yf:0,tUa:0,uqa:new _.wr,rZb:!1,RNa:Promise.resolve(),yK:new _.wr,entrypoint:null,ZB:null,header:null,Hl:[],kJa:!1,uuid:a.uuid,c9:!1,tL:void 0}};m2D=function(a,b,c){for(;c<a.length;c++)a[c].kJa=b};
s2D=function({client:a,Z4:b,v5e:c,x5e:d,stack:e}){var f=a.shellStyleClass,g=a.raa,h=a.plugin,{node:k,QH:l}=_.LQ(n=>{var q,r,t=(h==null?void 0:h.getType())===3,A=(r=(q=a.tL)==null?void 0:q.Aa())!=null?r:null;n2D(n);q="";A==null&&new _.QS;q+="<div"+_.X(o2D(n,t,A)+"PG8i1e ")+_.Y(p2D(n,t,A)+"")+_.W(q2D(n,t,A)+' role="dialog"')+">";t=r2D(n,t,A);A=n.Da();A!==""&&(q+=" <style>"+A+"</style>");q+=t+_.jC(n)+"</div>";n.Ea();return _.z(q)});g.Pnc({dispatch:l});k.setAttribute("data-svs","true");if(f)for(let n of f.split(" "))k.classList.add(n);
a.Lu=k;if(c){let {node:n,QH:q}=_.LQ(_.iZh);g.hA({dispatch:()=>void q({Cg:_.mF(k)})});k.appendChild(n);a.header=n}if(d){let {node:n,QH:q}=_.LQ(_.tZh);g.hA({dispatch:()=>void q({Cg:_.mF(k)})});k.appendChild(n);a.ZB=n}document.body.appendChild(k);c=e.indexOf(a)-e.length;a.QR=b.apply(a,c);return k};t2D=function(a){a.style.setProperty("--viewer-panel-height",`calc(${a.clientHeight}px - var(--jHHhxe, 0px))`)};
D2D=async function(a,b,c,d,e,f){var g=(0,_.Wf)(),h=g();g=g(1);try{let H=a.plugin,M=a.Lu,P=a.uqa,R=a.QR;if(R!==5)if(a.rZb)g(await h(P.promise));else{var k=a.viewerType===74;if(R===2){var l=_.Ov(_.Wv(_.Tv(new _.Xv,127),1),1,{replace:[6,...(k?[]:[7]),10]});a.entrypoint&&a.entrypoint instanceof HTMLElement&&_.rVb(l,a.entrypoint)}else{let Z=[2];_.PId&&Z.push(1);_.NId&&Z.push(3);_.OId&&Z.push(4);l=u2D(_.lVb(_.qVb(_.pVb(_.Uv(_.Tv(new _.Vv,1E3),R===3?1:2))),!_.EId&&a.contentPluginType!==5&&a.contentPluginType!==
19&&a.viewerType!==47&&a.viewerType!==73&&a.viewerType!==81&&!(_.CId&&a.viewerType===67)),{getScrollTopRequirement:()=>1,getShouldDisableScrolling:()=>!0,getSwipeToDismissDirections:()=>Z})}var n,q;_.iVb(_.Sv(_.Pv(_.Qv(l,[2]),e),(q=H==null?void 0:(n=H.VUe)==null?void 0:n.call(H))!=null?q:!0),5);var r=v2D?window.google.zl:void 0;if(R===2){e=_.iDd?0:250;var t=new w2D([{element:M,qx:"PyLEff",sJ:!0}],[{element:M,qx:"PyLEff",sJ:!1}],e,e,x2D(a,b))}else _.LId&&_.Nfh?t=new y2D(M,x2D(a,b)):_.MId&&_.Nfh?t=
new z2D(M,x2D(a,b)):t=new A2D(M,x2D(a,b));_.Rv(l,t);!B2D(a)&&d.isAvailable()&&R===1&&d.enterBasicMode(58);var A=c.open(M,l);P.resolve(A);a.rZb=!0;g(await h(P.promise));var E;r==null||(E=r.cqsv)==null||E.call(r);f();a.Yf>=5&&C2D(M)}}finally{h()}};B2D=function(a){var b=v2D?window.google.zl:void 0;return!(a.sjb===2||a.sjb===4)||!(b==null||!b.qsvo)};E2D=function(a){var b=a.plugin;(a=a.Lu)&&((b==null?0:b.qJd)?b.qJd():a.remove())};
H2D=function(a,b){var c=a.entrypoint;a=a.contentId;var d=b.at(-1);return d?F2D(d,G2D(d,b))===c?d.contentId&&a&&d.contentId!==a?!1:!0:!1:!1};I2D=function(a,b){for(let d=b.length-1;d>=0;d--){let {Lu:e}=b[d];var c;if(!(c=e==null?0:e.contains(a))&&(c=d===0&&b[d].viewerType===74&&e))a:{c=a.closest("[jsowner]");if(!c){c=!1;break a}c=(c=document.getElementById(c.getAttribute("jsowner")))?e.contains(c):!1}if(c)return d}return-1};G2D=function(a,b){a=b.indexOf(a);return a>0?b[a-1]:null};
J2D=function(a,b){if(a==null||b==null)return a===b;if(a.length!==b.length)return!1;for(let c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};F2D=function(a,b){if(a.entrypoint)return a.entrypoint;b=K2D(a.entrypointId,b);a.entrypoint=b;L2D(a);return b};L2D=function(a){var b;!a.entrypoint||(b=a.entrypoint)!=null&&b.querySelector("img, svg")||(a.c9=!0)};K2D=function(a,b){return a?(b=b?b.Lu:document.body)?b.querySelector(`[id="${a}"]`):null:null};
M2D=function(a,b){var c=a.entrypoint,d=a.replacedEntrypointId;return c&&c.isConnected?c:d?K2D(d,b):F2D(a,b)};
x2D=function(a,b){var c=b[0],d=G2D(a,b),e=!!d;return{eec:function(){var f,g,h=(f=a.plugin)==null?void 0:(g=f.R5a)==null?void 0:g.call(f,e),k;return{CHa:(k=h==null?void 0:h.CHa)!=null?k:M2D(a,d),Gib:h==null?void 0:h.Gib,Yma:(h==null?void 0:h.Yma)||a.kJa||B2D(a)||_.DId,EHa:h==null?void 0:h.EHa,QIc:a.c9,qgb:h==null?void 0:h.qgb}},Wcc:function(){var f,g,h=(f=a.plugin)==null?void 0:(g=f.ehb)==null?void 0:g.call(f,e);f=h==null?void 0:h.CHa;f===void 0&&(f=b.length===0?M2D(c,null):M2D(a,d));return{CHa:f,
Gib:h==null?void 0:h.Gib,Yma:(h==null?void 0:h.Yma)||a.kJa||_.DId,EHa:h==null?void 0:h.EHa,QIc:a.c9,qgb:h==null?void 0:h.qgb}}}};C2D=function(a){(0,_.jPa)().then(()=>{var b=_.Rma(a);_.J$i(b)})};N2D=function(){var a;((a=google)==null?0:a.uh)?google.uh("sv"):document.body.style.opacity=""};O2D=function(a){a.NBa!=null||(a.NBa=!1);a.c9!=null||(a.c9=!1);a.OOb!=null||(a.OOb=!1);a.viewerType!=null||(a.viewerType=void 0);a.source!=null||(a.source=void 0)};
P2D=function(a,b){var c=a.plugin,d=a.Lu;if(c){let e;c==null||(e=c.vMd)==null||e.call(c,a===b);let f;c==null||(f=c.setActive)==null||f.call(c,a===b)}d&&_.he(d,"hidden",a!==b)};u2D=function(a,b){a.Ea=b;return a};_.Kna=class extends Error{};Q2D={duration:250,easing:_.LTb};
w2D=class extends _.KTb{constructor(a,b,c,d,e){super();this.Ca=a;this.Aa=b;this.Ba=c;this.oa=d;this.config=e}async open(){var a=(0,_.Wf)(),b=a();a=a(1);try{let {Yma:c}=this.config.eec();_.eVb(this.Ca,c);c||a(await b(_.fVb(this.Ba)))}finally{b()}}async close(){var a=(0,_.Wf)(),b=a();a=a(1);try{let {Yma:c}=this.config.Wcc();_.eVb(this.Aa,c);c||a(await b(_.fVb(this.oa)))}finally{b()}}};R2D=function(a){var b;(b=a.Aa)==null||b.remove();a.Aa=void 0};
S2D=function(a,b,c=!1){if(!b||c)return a.Aa?a=a.Aa:(a.Aa=document.createElement("div"),a.Aa.style.opacity="0.0000001",a.Aa.style.height="100px",a.Aa.style.width="100px",a.Aa.style.position="fixed",a.Aa.style.top="50%",a.Aa.style.left="50%",a.Aa.style.marginTop="-100px",a.Aa.style.marginLeft="-100px",a.Aa.style.pointerEvents="none",document.body.appendChild(a.Aa),a=a.Aa),a;R2D(a);return b};
A2D=class extends _.KTb{constructor(a,b){super();this.overlay=a;this.config=b}async open(){var a=(0,_.Wf)(),b=a();a=a(1);try{let {CHa:d,Yma:e,qgb:f,EHa:g=_.OTb,QIc:h}=this.config.eec(),k=S2D(this,d,h);this.overlay.style.visibility="";if(!e){this.overlay.style.opacity="0";var c=f?_.PUb({elements:[this.overlay],kGb:!0,Osc:g}):_.RUb({token:g,before:k,after:this.overlay});a(await b(c.play()))}this.overlay.style.opacity="1"}finally{b()}}async close(){var a=(0,_.Wf)(),b=a();a=a(1);try{let {CHa:d,Yma:e,
qgb:f,EHa:g=Q2D,QIc:h}=this.config.Wcc(),k=S2D(this,d,h);if(!e){f||(k.style.opacity="0");var c=f?_.PUb({elements:[this.overlay],kGb:!1,Osc:g}):_.SUb({token:g,before:this.overlay,after:k});a(await b(c.play()))}(()=>{this.overlay.style.visibility="hidden";k.style.opacity="";R2D(this)})()}finally{b()}}};U2D=_.Mb(_.uQd);j2D=_.Mb(_.zQd);var z2D=class extends A2D{constructor(a,b){super(a,b);this.overlay=a;this.config=b}async open(){var a=(0,_.Wf)(),b=a();a=a(1);try{let {CHa:n,Yma:q}=this.config.eec(),r=()=>{this.overlay.style.visibility=""};if(q)r();else{var c=S2D(this,n).getBoundingClientRect(),d={},e=_.Lfh(r,{root:d});a(await b(e.updateCallbackDone));var f=document.body.getBoundingClientRect(),g,h=((g=this.overlay.querySelector('[jsname="figiqf"]'))==null?void 0:g.getBoundingClientRect())||f,{cJe:k,aIe:l}=d2D(c,Object.assign({},
h.toJSON(),{left:0}));d.bBa={animation:k};d.new={animation:l}}}finally{b()}}async close(){var a=(0,_.Wf)(),b=a();a=a(1);try{let {CHa:e,Yma:f}=this.config.Wcc(),g=S2D(this,e),h=()=>{this.overlay.style.visibility="hidden";g.style.opacity=""};if(f)h();else{var c=window.getComputedStyle(document.body).backgroundColor,d=_.Lfh(h,{groups:[{element:this.overlay,fRb:()=>g,group:{styles:{overflow:"hidden",backgroundColor:c,borderRadius:"16px"}},Ueb:2,ozc:!0}]});a(await b(d.finished))}}finally{b()}}},W2D=async function(a){var {CHa:b,
Gib:c,Yma:d}=a.config.Wcc(),e=S2D(a,b);if(d)a.overlay.style.visibility="hidden",e.style.opacity="";else{var f={duration:250,easing:"cubic-bezier(.5,1,.5,.9)",fill:"both"},g=(c||a.overlay).getBoundingClientRect(),h={new:{animation:{keyframes:[{offset:0,transform:"scale(1.2)",opacity:"0"},{offset:1,transform:"scale(1)",opacity:"1"}],options:f}}},k=e2D({element:c||a.overlay,Zua:e,fBd:c,grd:()=>e,containment:!1,Ueb:1,ozc:!0,options:f});return new Promise(l=>{a.Ba=_.Lfh(()=>{a.overlay.style.visibility=
"hidden";e.style.opacity=""},{Xve:!0,root:h,groups:[k],updateCallbackDone:n=>{var q=S2D(a,b).getBoundingClientRect(),r=q.width/g.width;n.root.bBa={animation:{keyframes:[{transform:"translate(0px, 0px) scale(1)",transformOrigin:"top left"},{transform:`translate(${q.left-0*r}px, ${q.top-g.top*r}px) scale(${r})`,transformOrigin:"top left"}],options:Object.assign({},f,{id:"close-root-old"})},styles:{zIndex:"1"},lzc:[{keyframes:[{opacity:1},{opacity:0}],options:f}]};a.oa={K9c:a.Ba,vud:k,Lna:[],qYb:[],
Jea:{},Il:{}};l()},finished:()=>{V2D(a);var n,q;(n=a.oa)==null||(q=n.Qb)==null||q.remove();a.oa=void 0}})})}},X2D=function(a){var b;(b=a.oa)==null||b.K9c.skipTransition();V2D(a);var c,d;(c=a.oa)==null||(d=c.Qb)==null||d.remove();a.oa=void 0;a.overlay.style.visibility=""},Y2D=function(a,b){a.oa&&(b(a.oa.Jea),b(a.oa.Il))},V2D=function(a){var b;(b=a.oa)==null||b.Lna.forEach(c=>{c.cancel()})},y2D=class extends A2D{constructor(a,b){super(a,b);this.overlay=a;this.config=b;this.swipeToDismiss={onStart:async()=>
{var c=(0,_.Wf)(),d=c();c=c(1);try{if(c(await d(W2D(this))),this.oa){c(await d(this.oa.K9c.ready));this.oa.Lna=_.Dfh();var e=`::view-transition-group(${this.oa.vud.viewTransitionName})`;this.oa.Jea.animation=this.oa.Lna.find(g=>g.effect.pseudoElement===e);this.oa.Il.animation=this.oa.Lna.find(g=>g.id==="close-root-old");if(!this.oa.Jea.animation)throw X2D(this),Error("SE");if(!this.oa.Il.animation)throw X2D(this),Error("TE");this.oa.qYb=this.oa.Lna.filter(g=>g!==this.oa.Jea.animation&&g!==this.oa.Il.animation);
for(let g of this.oa.Lna)g.pause();var f=document.createElement("style");this.oa.Qb=f;document.head.appendChild(f);this.oa.Jea.rule=_.Efh(f,`html::view-transition-group(${this.oa.vud.viewTransitionName})`,{});this.oa.Il.rule=_.Efh(f,"html::view-transition-old(root)",{});Y2D(this,g=>{var h=new DOMMatrix(window.getComputedStyle(document.documentElement,g.animation.effect.pseudoElement).transform);g.Jo=_.vfh(h)})}}finally{d()}},onMove:async c=>{if(this.oa&&this.oa.Lna.length){var d=this.oa.Lna[0].effect.getTiming().duration;
d=Math.min(Math.max(d*c.yWithTension/4E3,0),d/3);for(let e of this.oa.qYb)e.currentTime=d;Y2D(this,({rule:e,Jo:f})=>{e.style.setProperty("transform",`${`translate(${c.xWithTension+f.left}px, ${c.yWithTension+f.top}px)`} scale(${f.zQ*c.scale}, ${f.DQ*c.scale})`,"important")})}},onDismiss:()=>{if(this.oa){Y2D(this,({animation:e,rule:f})=>{var g=e.effect,h=g.getKeyframes();h[0].transform=f.style.transform;g.setKeyframes(h);g=e.effect.getTiming().duration;var k=Math.max(this.oa.qYb[0].currentTime,100);
e.cancel();document.documentElement.animate([{transform:f.style.transform},{transform:h[1].transform}],{easing:"cubic-bezier(.5,1,.5,.9)",duration:g-k,fill:"both",pseudoElement:e.effect.pseudoElement})});var c,d;(c=this.oa)==null||(d=c.Qb)==null||d.remove();for(let e of this.oa.Lna)e.play()}},onCancel:()=>{if(this.oa){var c=Math.max(this.oa.qYb[0].currentTime,100),d;Y2D(this,({animation:g,rule:h})=>{d=document.documentElement.animate([{transform:h.style.transform},{transform:""}],{easing:"cubic-bezier(.5,1,.5,.9)",
duration:c,fill:"both",pseudoElement:g.effect.pseudoElement})});var e,f;(e=this.oa)==null||(f=e.Qb)==null||f.remove();for(let g of this.oa.qYb)g.currentTime=Math.max(g.currentTime,1),g.reverse();d.finished.then(()=>{X2D(this)})}}}}async open(){var a=(0,_.Wf)(),b=a();a=a(1);try{let c;a(await b((c=this.Ca)==null?void 0:c.finished))}finally{b()}}async beforeOpen(){var {CHa:a,Gib:b,Yma:c}=this.config.eec();if(c)this.overlay.style.visibility="";else{var d={duration:250,easing:"cubic-bezier(.5,1,.5,.9)",
fill:"both"},e=S2D(this,a),f=e.getBoundingClientRect(),g={bBa:{animation:{keyframes:[{offset:0,transform:"scale(1)",opacity:"1"},{offset:1,transform:"scale(1.2)",opacity:"0"}],options:d}}},h=e2D({element:e,Zua:b||this.overlay,fBd:e,grd:()=>b,containment:!1,Ueb:1,options:d});return new Promise(k=>{this.Ca=_.Lfh(()=>{k();this.overlay.style.visibility=""},{gmd:!0,root:g,groups:[h],updateCallbackDone:l=>{var n=(b||this.overlay).getBoundingClientRect(),q=f.width/n.width;l.root.new={animation:{keyframes:[{transform:`translate(${f.left-
0*q}px, ${f.top-n.top*q}px) scale(${q})`,transformOrigin:"top left"},{transformOrigin:"top left"}],options:d},lzc:[{keyframes:[{opacity:0},{opacity:1}],options:{delay:100,duration:150,fill:"both",easing:"cubic-bezier(.34,.69,.34,1)"}}]}}})})}}async close(){var a=(0,_.Wf)(),b=a();a=a(1);try{this.oa||a(await b(W2D(this))),this.oa&&a(await b(this.oa.K9c.finished))}finally{b()}}};var q2D=function(a,b,c){b="";c==null&&new _.QS;return b+=' jsname="'+_.T("ujKaBc")+'" decode-data-ved="'+_.T("1")+'"'+_.iC(a,{Hb:233502,track:[4,3]}).attributes},o2D=function(a,b,c){c==null&&new _.QS;return""},p2D=function(a,b,c){c==null&&new _.QS;return""},Z2D=function(a,b,c){c==null&&new _.QS;return!0},$2D=function(a,b,c){c==null&&new _.QS;return!1},a3D=function(a,b){n2D(a);return r2D(a,b.Vvd,b.iBa)},b3D=function(a,b){n2D(a);var c=b.Vvd,d=b.iBa;b="";d==null&&new _.QS;b+="<div"+_.X(o2D(a,c,d)+"PG8i1e ")+
_.Y(p2D(a,c,d)+"")+_.W(q2D(a,c,d)+' role="dialog"')+">";c=r2D(a,c,d);b+=c+_.jC(a)+"</div>";return _.z(b)},r2D=function(a,b,c){c=c==null?new _.QS:c;var d=_.CC(_.si().Xa),e=_.CC(_.si().OG),f=_.CC(_.si().Yk),g=_.CC(_.si().Bn),h=_.CC(_.si().Nc);a.Ba(".Ksi7Wb{background-color:"+_.V(d,"",k=>k.QI())+"}");a.Ba(".PG8i1e{background:"+_.V(d,"",k=>k.Wc())+";overflow:hidden;position:fixed;transform:translateX(0)}");a.Ba(".FRA6xd{overflow-y:auto}");a.Ba(".PG8i1e.Ooz8t{"+((_.R$h?"border:1px solid "+_.V(d,"",k=>
k.Eo())+";border-radius:24px;box-shadow:none;opacity:0.001;transition:transform "+_.V(g,"",k=>_.u(k,49))+" "+_.V(g,"",k=>_.u(k,56))+",opacity "+_.V(g,"",k=>_.u(k,49))+";":"")+(_.iDd&&!_.R$h?"border:1px solid "+_.V(d,"",k=>k.Eo())+";border-radius:"+_.V(f,"",k=>_.YRc(k))+";box-shadow:none;":"")+(_.iDd&&_.QXh?"transform:translateX(-50%);opacity:0.001;transition:transform 350ms cubic-bezier(0.20,0.00,0.00,1.00) 0ms,opacity 50ms cubic-bezier(0.31,0.94,0.34,1.00) 0ms;":"")+(_.iDd&&_.RXh?"transform:translateX(75%);opacity:0.001;transition:transform 350ms cubic-bezier(0.20,0.00,0.00,1.00) 0ms,opacity 50ms cubic-bezier(0.31,0.94,0.34,1.00) 0ms;":
"")+(_.iDd||_.R$h?"":"border-radius:"+_.V(f,"",k=>_.YRc(k))+";box-shadow:"+_.V(e,"",k=>_.u(k,8))+";opacity:0.001;transform:translateX(200px);transition:transform 250ms cubic-bezier(0.05,0.07,0.1,1),opacity 250ms;")+(!_.iDd&&_.QXh?"transform:translateX(-50%);opacity:0.001;transition:transform 350ms cubic-bezier(0.20,0.00,0.00,1.00) 0ms,opacity 50ms cubic-bezier(0.31,0.94,0.34,1.00) 0ms;":"")+(!_.iDd&&_.RXh?"transform:translateX(75%);opacity:0.001;transition:transform 350ms cubic-bezier(0.20,0.00,0.00,1.00) 0ms,opacity 50ms cubic-bezier(0.31,0.94,0.34,1.00) 0ms":
"")+"}"));a.Ba(".Ooz8t.F6z1Rc{box-shadow:"+_.V(e,"",k=>_.Qtc(k))+"}");a.Ba(".PG8i1e.Ooz8t.PyLEff{opacity:0.999;"+(_.iDd?"":"transform:translateX(0);")+(!_.iDd&&_.QXh?"transform:translateX(0);opacity:0.999;transition:transform 500ms cubic-bezier(0.05,0.70,0.10,1.00) 0ms,opacity 150ms cubic-bezier(0.31,0.94,0.34,1.00) 100ms;":"")+(!_.iDd&&_.RXh?"transform:translateX(0);opacity:0.999;transition:transform 500ms cubic-bezier(0.05,0.70,0.10,1.00) 0ms,opacity 150ms cubic-bezier(0.31,0.94,0.34,1.00) 100ms;":
"")+(_.iDd&&_.QXh?"transform:translateX(0);opacity:0.999;transition:transform 500ms cubic-bezier(0.05,0.70,0.10,1.00) 0ms,opacity 150ms cubic-bezier(0.31,0.94,0.34,1.00) 100ms;":"")+(_.iDd&&_.RXh?"transform:translateX(0);opacity:0.999;transition:transform 500ms cubic-bezier(0.05,0.70,0.10,1.00) 0ms,opacity 150ms cubic-bezier(0.31,0.94,0.34,1.00) 100ms":"")+"}");a.Ba(".MiFXAd{"+((_.oA?"background:"+_.V(d,"",k=>k.YX())+";":"")+(_.oA?"":"background:rgba(255,255,255,0.6);")+"display:flex;justify-content:center;align-items:center;backdrop-filter:blur(8px);position:fixed;top:0;left:0;width:100%;height:100%}"));
a.Ba(".QtrPTd{width:80%;height:calc(100% - 150px);top:75px;bottom:75px;left:10%}");a.Ba(".fLi1af{background:"+_.V(d,"",k=>k.Wc())+";border-radius:12px}");a.Ba(".Yktdff{"+((!_.Q$h||_.oA?"background:#101218;color:"+_.V(d,"",k=>_.UA(k))+";":"")+(_.Q$h&&!_.oA?"background:"+_.V(d,"",k=>k.Wc())+";color:"+_.V(d,"",k=>_.qp(k))+";":"")+"position:fixed;top:0;left:0;width:100%;height:100%}"));a.Ba(!_.Q$h||_.oA?".Yktdff .VB2c0b{color:"+_.V(d,"",k=>k.e4())+"}":"");a.Ba(".eQVlOe{padding-left:"+(_.V(h,"",k=>_.lB(k))+
";padding-right:"+_.V(h,"",k=>_.lB(k))+"}"));a.Ba(_.a2D?".PG8i1e.Ooz8t.X3bDbe{border:1px solid "+_.V(d,"",k=>k.Eo())+";box-shadow:none;border-radius:24px;margin-top:20px;margin-bottom:20px}":"");d="";b&&_.B1h(a,c)&&(b="<div"+_.X(_.z1h(a,c)+"HV5Yde ")+_.Y(_.A1h(a,c)+"")+_.W(_.y1h(a,c)+"")+">"+_.E1h(a,c)+"</div>",d+=_.C1h(a,c)?"":b);return d+=_.jC(a)},n2D=function(a){a.oa(c3D)||(a.Aa(c3D,{Vvd:0,iBa:1},a3D,b3D,Z2D,$2D,' role="dialog"',q2D,"PG8i1e ",o2D,"",p2D),_.D1h(a))},c3D="t-_7Z7QKitJBk";var e3D=function(a){if(a.mode===1)return a;a.mode=1;a.raa=new d3D;return a},k2D=class{constructor(){this.mode=1;this.raa=new d3D}aab(a,b,c){this.raa.aab(a,b,c);return this}ypb(){this.mode=0;this.raa=this.raa.ypb();return this}Pnc(a){this.raa.Pnc(a)}hA(a){this.raa.hA(a)}},f3D=class{constructor(a,b,c){this.interactionVed=a;this.Cg=b;this.tA=c}Pnc(a){a.dispatch({interactionVed:this.interactionVed,Cg:this.Cg,uVa:!0,tA:this.tA})}hA(a){a.dispatch()}aab(a,b,c){this.interactionVed=a;this.Cg=b;this.tA=c}ypb(){return this}},
d3D=class{constructor(){this.oa=[]}Pnc(a){this.Aa=a}hA(a){this.oa.push(a)}aab(a,b,c){this.interactionVed=a;this.Cg=b;this.tA=c}ypb(){var a=this.interactionVed,b=this.Cg,c=this.tA,d;(d=this.Aa)==null||d.dispatch({interactionVed:a,Cg:b,uVa:!0,tA:c});this.oa.forEach(e=>void e.dispatch());return new f3D(a,b,this.tA)}};var v2D,g3D,k3D,l3D,j3D,n3D,s3D,p3D,t3D,v3D,y3D,w3D,x3D,i3D,u3D,m3D,A3D,r3D,h3D,q3D,z3D,B3D,o3D;v2D=_.JId||_.KId;g3D=function(a){return a.oa.at(-1)};
k3D=function(a,b,c){var d=G2D(b,a.oa),e=b.QR;_.Sg(c,"KpPeYd",f=>{a.Li(b,f.data)});_.Sg(c,"YS2dOd",f=>{h3D(a,b,2,f);i3D(a,b,2)});_.Sg(c,"gZgazf",f=>{h3D(a,b,1,f);i3D(a,b,1)});b.yK.promise.then(()=>{b.tUa=0;try{var f;let g;(f=b.plugin)==null||(g=f.JPa)==null||g.call(f)}catch(g){}b.FP.abort();(_.QId||_.XZd)&&a.Z4.Cab(b);E2D(b);for(let g of b.Hl)_.Vn(g);if(e===1||_.gA&&e===4)f=F2D(b,d),!f||b.Lu&&!b.Lu.contains(document.activeElement)&&document.activeElement!==document.body||j3D(f);(0,_.jPa)().then(()=>
{_.K$i();(0,_.uh.dirty)()})});_.Sg(c,"ucVTnf",()=>{var f=b.plugin,g=b.rZ,h=a.oa,k=F2D(b,d),l=g2D(4,g)===1,n,q=(n=G2D(b,h))==null?void 0:n.Lu;l&&q&&(q.style.display="");var r;(f==null?0:(r=f.YYb)==null?0:r.call(f,k))||!k||b.c9||(k.style.opacity="0");if(f==null?0:f.PDb)var t=_.Ug(c,"pU3PWb",()=>{var A;return void(f==null?void 0:(A=f.PDb)==null?void 0:A.call(f,k))});_.Ug(c,"s2IYHc",()=>{t&&_.Tg(t);var A;(f==null?0:(A=f.Vlc)==null?0:A.call(f,k))||!k||b.c9||(k.style.opacity="");l&&q&&(q.style.display=
"none")})});t2D(c);b.Hl.push(_.Be(window,"resize",_.Zn(()=>{t2D(c);if(_.lJd){var f=a.oa;f=f.indexOf(b)-f.length;b.QR=a.Z4.apply(b,f)}},100)))};l3D=function(a,b,c){G2D(b,a.oa)&&c.classList.add("L3JeZd");var d,e;((d=b.tL)==null?0:(e=d.Aa())==null?0:_.B(e,1))&&c.style.setProperty("--jHHhxe",_.aWh);_.$Vh(c)};
j3D=function(a,b,c=!1){if(c){c=b.pG;c||(b.pG=new _.Odc(a),_.Ldc(b.pG),c=b.pG);let d;(d=_.Ndc(c))==null||d.focus({preventScroll:!0})}else b=document.activeElement,a.contains(b)&&a!==b||(a.tabIndex===0?a.focus({preventScroll:!0}):(b=_.Adc(a).find(d=>!d.hasAttribute("data-os-fs")))?b.focus({preventScroll:!0}):(a.tabIndex=-1,a.focus({preventScroll:!0})))};
n3D=async function(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let e=g3D(a);if(e){e.sjb=3;var d=c2D(a.oe);e3D(e.raa).aab(d,d);_.HId||e.raa.ypb();document.dispatchEvent(new CustomEvent("viewerOpened"));b(await c(m3D(a,e)))}}finally{c()}};
s3D=async function(a,b,c=!1){var d=(0,_.Wf)(),e=d();d=d(1);try{_.eJd||(c=!1);let g=a.oa,h=b.length<g.length,k=b.length>g.length,l=Math.min(b.length,g.length),n=l;for(let q=0;q<l;q++)if(g[q].uuid!==b[q].uuid){h=k=!0;n=q;break}m2D(g,c,n);if(h&&!k){var f=g[n];let q,r,t,A=(t=(q=f.plugin)==null?void 0:(r=q.fhb)==null?void 0:r.call(q))!=null?t:o3D(a,f);a.oe.logEvent({He:new _.Uh(A,26)})}h&&p3D(a,n);if(k){let q=b.slice(n).map(l2D);for(let r=q.length-1;r>=0;r--)if(q[r].uuid===a.Ba){d(await e(q3D(a,1)));return}g.push(...q);
m2D(g,c,n)}a.Ba=-1;(k||h)&&d(await e(r3D(a,k)));a.Ca&&(a.Ca.resolve(),a.Ca=null)}finally{e()}};
p3D=function(a,b,c=!1){b=a.oa.splice(b,Infinity);var d,e=(d=g3D(a))==null?void 0:d.Lu;e&&(e.style.display="");if(b.length!==0){a.Ba=b[0].uuid;a.oa.length!==0||c?c&&document.dispatchEvent(new CustomEvent("viewerReplaced")):document.dispatchEvent(new CustomEvent("viewerClosed"));for(let f of b)c=f.Lu,d=f.rZb,b=f.yK,P2D(f,null),c&&d?((d=f.pG)&&_.Mdc(d),f.Lu&&!f.Lu.contains(document.activeElement)||document.activeElement.blur(),a.Me.close(c)):b.resolve();if(_.U1D){let f,g,h;(f=window.google)==null||(g=
f.aegis)==null||(h=g.checkpoint)==null||h.call(g,_.ZVh.Ef())}}};t3D=function(a,b){return i2D(a.ej,a.oa,b)};v3D=async function(a,b,c){var d=(0,_.Wf)(),e=d();d=d(1);try{let f=u3D(a,b);m2D(a.oa,!0,b);p3D(a,b,!0);if(c.OOb&&f===1)return!0;d(await e(a.ej.go(-f)));return!1}finally{e()}};
y3D=async function(a,b,c,d=!1){var e=(0,_.Wf)(),f=e();e=e(1);try{let g=b.pC,h=b.entrypoint,k=b.interactionVed,l=b.tA,n=b.Vx,q=b.rZ,r=a.oa;for(let M of r)M.tUa=M.Yf;let t=_.w_h(h),A=_.mF(h),E,H={viewerType:b.viewerType,modalityOverride:b.modalityOverride,serializedModalityOverride:void 0,rZ:q,serializedCloseConfig:q?U2D(q):void 0,shellStyleClass:b.shellStyleClass,Lu:null,plugin:g,FP:new AbortController,contentPluginType:g.getType(),content:((E=g.serialize)==null?void 0:E.call(g))||new Uint8Array(0),
entrypointId:t,contentId:b.contentId,replacedEntrypointId:void 0,raa:(new k2D).aab(k!=null?k:A,A,l),interactionVed:k!=null?k:A,sjb:2,Yf:3,tUa:7,uqa:new _.wr,rZb:!1,RNa:null,yK:new _.wr,entrypoint:h,ZB:null,header:null,Hl:[],kJa:c,uuid:Math.random(),c9:b.c9,tL:b.tL,ZPe:d};_.HId||H.raa.ypb();L2D(H);r.push(H);r.length===1&&document.dispatchEvent(new CustomEvent("viewerOpened"));a.aJ&&_.rK(a.aJ,_.HFe);try{e(await f(w3D(a,{client:H,Vx:n}))),(0,_.kPa)(()=>void x3D(a))}catch(M){e()}return H.Lu}finally{f()}};
w3D=function(a,{client:b,Vx:c}){var d;c==null||c.Hx((d=b.viewerType)!=null?d:0);a=_.u0h({client:b,Vx:c,rPb:a.rPb});_.U1D&&a.then(()=>{var e,f,g;(e=window.google)==null||(f=e.aegis)==null||(g=f.checkpoint)==null||g.call(f,_.ZVh.Ef())},()=>{var e,f,g;(e=window.google)==null||(f=e.aegis)==null||(g=f.checkpoint)==null||g.call(f,_.ZVh.Ef())});return a};
x3D=async function(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let e=a.oa;if(!(e.length<2||e.at(-1).Yf<7)){var d=e.at(-2);if(!d.FP.signal.aborted&&d.Yf<7)try{d.sjb=1,e3D(d.raa),d.tUa=7,b(await c(w3D(a,{client:d})))}catch(f){b()}}}finally{c()}};
i3D=async function(a,b,c,{zub:d=!1,eDc:e}={}){var f=(0,_.Wf)(),g=f();f=f(1);try{if(d||b===g3D(a)){var h=d?0:z3D(a,b,c),k=u3D(a,h);d?m2D(a.oa,!0,h):b.kJa=!1;e&&(a.Ca=e);var l=a.oa.slice(h);p3D(a,h);var n=q3D(a,k);f(await g(n3D(a)));f(await g(n));if(e){let q=l.map(r=>r.yK.promise);f(await g(Promise.all([e.promise,...q])))}if(!g3D(a)){let q=document.head.querySelector('link[rel="canonical"]');q&&document.head.removeChild(q)}}}finally{g()}};
u3D=function(a,b){for(var c=0;b<a.oa.length;b++)a.oa[b].RNa&&c++;return c};m3D=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let e=b.Lu;e&&(e.style.display="");b.tUa=7;c(await d(w3D(a,{client:b,Vx:new _.iAj})));(0,_.kPa)(()=>void x3D(a))}finally{d()}};A3D=function(a,b){return(b=F2D(b,G2D(b,a.oa)))?_.mF(b):c2D(a.oe)};
r3D=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{let l=g3D(a);if(l){_.ZId&&l.interactionVed&&_.mq(a.oe.oa(),new _.Uh(l.interactionVed)).log();if(b){l.sjb=4;var e=e3D(l.raa),f=e.aab;var g=a.oe;if(T2D)var h=T2D;else{var k=_.Ve(_.Tm("iGkMSe"));h=T2D=_.q0h(g,251479,k)}f.call(e,h,A3D(a,l));document.dispatchEvent(new CustomEvent("viewerOpened"))}else l.sjb=5,e3D(l.raa).aab(c2D(a.oe),A3D(a,l));_.HId||l.raa.ypb();c(await d(m3D(a,l)))}}finally{d()}};
h3D=function(a,b,c,d){var e=null;if(c===1){let f,g;e=((f=b.plugin)==null?void 0:(g=f.A6)==null?void 0:g.call(f))||null}else if(c===2){let f,g;e=((f=b.plugin)==null?void 0:(g=f.r5a)==null?void 0:g.call(f))||null}e||(e=d.targetElement.Za());_.nq(a.oe.oa(),e,3).log()};q3D=async function(a,b){var c=(0,_.Wf)(),d=c();c=c(1);try{b>0&&(c(await d(a.ej.go(-b))),_.Zg(document.body,"nOJPYb"))}finally{d()}};z3D=function(a,b,c){b=g2D(c,b.rZ);switch(b){case 1:return a.oa.length-1;case 2:return 0;default:return _.Ya(b)}};
B3D=function(a,b){var c,d,e,f=(e=(c=b.plugin)==null?void 0:(d=c.fhb)==null?void 0:d.call(c))!=null?e:o3D(a,b);(0,_.If)(()=>{a.oe.logEvent({He:new _.Uh(f,21)})})};o3D=function(a,b){if(b.Bub)return b.Bub;var c=_.zqb(b.Lu);return b.Bub=_.q0h(a.oe,3593,c)};
_.C3D=class extends _.Jo{static Ta(){return{service:{overlay:_.Kv,history:_.WOs,Df:_.pv,logging:_.lv,QR:_.S1D,iA:_.b$p,Bma:_.T1D}}}constructor(a){super();this.aJ=null;this.Ba=-1;this.Ca=null;this.rPb={isActive:d=>d===g3D(this),Egd:d=>!this.Da.bRc(d.contentPluginType),fjd:d=>{var e=s2D({client:d,Z4:this.Z4,v5e:!0,x5e:!0,root:G2D(d,this.oa),stack:this.oa});k3D(this,d,e);l3D(this,d,e);return e},hjd:d=>{var e=d.plugin;e=this.Da.bRc(d.contentPluginType)?e.MPe():s2D({client:d,Z4:this.Z4,root:G2D(d,this.oa),
stack:this.oa});k3D(this,d,e);l3D(this,d,e);return d.Lu=e},uBd:d=>this.Vla(d.contentPluginType),DPc:async(d,e)=>{var f=(0,_.Wf)(),g=f();f=f(1);try{d.plugin=f(await g(e.FA(d.content,h=>this.Vla(h))))}finally{g()}},Snd:async d=>{var e=(0,_.Wf)(),f=e();e=e(1);try{let g=d.plugin,h=d.FP,k;e(await f((k=g.fetch)==null?void 0:k.call(g,{signal:h.signal})))}finally{f()}},dC:d=>{var e=d.plugin,f=d.Lu,g=d.FP,h=d.ZB,k=d.header,l=d.raa,n={status:0,source:0};if(e.Aid){let q,r,t=(r=(q=e.Dbg)==null?void 0:q.call(e))!=
null?r:new Map;e.Aid(this.Un(),A=>this.Vla(A),t)}if(e.dC!=null){n=e.dC({Il:f,signal:g.signal,hA:H=>void l.hA(H)});n.status!==0&&(h==null||h.remove(),k==null||k.remove());let q,r,t,A,E;(r=_.DOa(f))==null||(t=r.Cc("ct",`sv_prvw:${(A=n.source)!=null?A:0},${(E=e==null?void 0:(q=e.getViewerType)==null?void 0:q.call(e))!=null?E:0}`))==null||t.log()}n.status===2&&d.rZb&&C2D(f);return n.status},render:async d=>{var e=(0,_.Wf)(),f=e();e=e(1);try{let g=d.plugin,h=d.Lu,k=d.FP,l=d.ZB,n=d.header,q=d.raa;l==null||
l.remove();n==null||n.remove();g.render!=null&&e(await f(g.render({Il:h,signal:k.signal,hA:r=>void q.hA(r)})));if(_.FId&&!h.querySelector('[jsname="OXxrqc"]')){let r=document.body.querySelector('[jsname="yloBKd"]');(r==null?0:r.firstElementChild)&&h.appendChild(r.firstElementChild.cloneNode(!0))}d.uqa.promise.then(()=>{(0,_.jPa)().then(()=>{_.vr()})})}finally{f()}},vnb:()=>{},PXc:async(d,e)=>{var f=(0,_.Wf)(),g=f();f=f(1);try{f(await g(D2D(d,this.oa,this.Me,this.Wk,this.onDismiss(d),e)));let n=this.oa,
q=n.indexOf(d);if(q!==-1){var h=g3D(this);for(e=0;e<q;e++){let r=n[e],t=r.Lu;t&&(t.style.display="none");P2D(r,h)}var k=d.plugin,l=d.Lu;P2D(d,h);j3D(l,d,!("function"==typeof _.R2h&&k instanceof _.R2h)&&_.gA);_.U1D&&(0,_.jPa)().then(()=>{(0,_.Ao)(()=>{var r,t,A;(r=window.google)==null||(t=r.aegis)==null||(A=t.checkpoint)==null||A.call(t,_.ZVh.Ef())},200)})}}finally{g()}},F_b:d=>{this.F_b(d)},Tkd:d=>{_.HId&&d.raa.ypb()}};this.Me=a.service.overlay;this.ej=a.service.history;this.Wk=a.service.Df;this.oe=
a.service.logging;this.Z4=a.service.QR;this.Da=a.service.Bma;if(v2D){let d,e,f;(d=window.google)==null||(e=d.zl)==null||(f=e.qsvd)==null||f.call(e)}this.isRtl=document.body&&_.te(document.body);var {layers:b,p3c:c}=this.ej.Fdc(this.Z4);this.oa=b.map(l2D);n3D(this).catch(()=>{});c&&N2D();this.ej.addListener((d,e)=>{s3D(this,d,e).catch(()=>{})});document.addEventListener("viewerGuestClose",()=>{p3D(this,0);t3D(this,{replace:!1}).catch(()=>{})});_.Sg(document.body,"gZgazf",this.OWa,this)}async Z5(){var a=
(0,_.Wf)(),b=a();a=a(1);try{if(super.Z5(),_.GId){let c=a(await b(_.eGe(_.Jr,this.Un())));c&&(this.aJ=new _.KFe(c))}}finally{b()}}Um(){var a=this.ej;if(_.LOs())var b=_.ZVh.Ef();else{var {RNa:c,url:d}=a.get();a=(b=c==null?void 0:c.at(-1))!=null?b:d==null?void 0:d.at(-1);b=new _.Gu(_.ZVh.Ef());a?(b.pathname=`/searchviewer/${a.viewerType}`,b.searchParams.set("svid",_.OOs(a,void 0,!0)),b.searchParams.delete("q"),b.searchParams.delete("udm"),b.oa.delete("sv"),b=b.toString()):b=null}return b}aSb(){var a;
{let {RNa:d,url:e}=this.ej.get(),f=(a=d==null?void 0:d.at(-1))!=null?a:e==null?void 0:e.at(-1);f?a=_.NOs(f,void 0,_.LOs()):(_.LOs(),a=null)}var b,c;return{content:(b=a==null?void 0:_.Hb(a.getContent()))!=null?b:new Uint8Array(0),contentPluginType:(c=a==null?void 0:a.getContentPluginType())!=null?c:null}}async prefetch(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let d=b(await c(this.Ljc(a)));b(await c(Promise.all(d.map(async e=>{var f;return await ((f=e.prefetch)==null?void 0:f.call(e))}))))}finally{c()}}async Ljc(a){var b=
(0,_.Wf)(),c=b();b=b(1);try{let d={};a.forEach(f=>{d[String(f)]=this.Da.lLc(f)});let e=b(await c(_.dg(this,{service:d})));return Object.values(e.service)}finally{c()}}async Vla(a){return await _.eg(this.Da.lLc(a),this.Un())}Aa(){}async showViewerLite(a){var b=(0,_.Wf)(),c=b();b=b(1);try{let d=this.Vla(a.contentPluginType),e,f=b(await c(d));if(a.xIb){let g=_.A_h(a.entrypoint);if(!g)throw Error("RE`"+a.entrypoint);let h=b(await c(f.FA(a.Wqa,l=>this.Vla(l),{index:_.H_h(g,a.entrypoint),count:g.fea()}))),
k=b(await c(this.Vla(3)));e=b(await c(k.getInstance({index:_.H_h(g,a.entrypoint),gjb:h,lS:g})))}else e=b(await c(f.FA(a.Wqa,g=>this.Vla(g))));b(await c(this.showViewer({pC:e,vda:a.vda,entrypoint:a.entrypoint,interactionVed:a.interactionVed,Vx:void 0,tA:a.tA,NBa:a.NBa,viewerType:a.viewerType,modalityOverride:a.modalityOverride,shellStyleClass:a.shellStyleClass,rZ:a.rZ,source:a.source,contentId:a.contentId,c9:a.c9,tL:a.tL,OOb:void 0})))}finally{c()}}async showViewer(a){var b=(0,_.Wf)(),c=b();b=b(1);
try{let d,e;if(v2D&&((d=window.google)==null?0:(e=d.zl)==null?0:e.qsvoc))return window.google.zl.qsvoc--,Promise.reject(new _.Kna("search-viewer: quick viewer was closed"));a.vda!=null&&_.$2h(a.vda);let f;a.Vx||(a.Vx=_.jAj((f=a.entrypoint.getAttribute("data-ep-type"))!=null?f:"",a.vda));O2D(a);let g=a.entrypoint,h=a.NBa,k=a.rZ,l=this.oa;this.Ba=-1;if(H2D(a,l)){let r,t;return Promise.resolve((t=(r=g3D(this))==null?void 0:r.Lu)!=null?t:null)}let n=(k==null?0:_.B(k,6))?l.length-1:I2D(g,l),q=h?Math.max(0,
n):n+1;if(q<l.length){let r,t=g3D(this),A=null,E=_.Lfh(async()=>{var H=(0,_.Wf)(),M=H();H=H(1);try{let P=h?l[q].entrypointId:void 0,R=H(await M(v3D(this,q,a)));r=y3D(this,a,!0,R);A=g3D(this);A.replacedEntrypointId=P;H(await M(A.uqa.promise))}finally{M()}},{root:{disable:!0},groups:[{element:t.Lu,fRb:()=>A.Lu,group:{styles:{animationDuration:"150ms"}}}]});b(await c(E.updateCallbackDone));return r}return y3D(this,a,!1)}finally{c()}}OWa(a){a=a.data;if(typeof a!=="boolean"){var b=a.eDc;if(a.zub)this.oa.length===
0?b==null||b.resolve():i3D(this,this.oa[0],0,a).catch(c=>{b&&b.reject(c)});else if(b){let c=g3D(this);c?i3D(this,c,0,a).catch(d=>{b.reject(d)}):b.resolve()}}}m5a(){var a=g3D(this),b="";try{if(a==null?0:a.Lu)for(let f of a.Lu.querySelectorAll("[data-sv-ctx]"))b+=" "+(f.textContent||"");let c,d,e=(a==null?void 0:(c=a.plugin)==null?void 0:(d=c.m5a)==null?void 0:d.call(c))||new Map;e.has("prompt_text")||(b=b+" "+(e.get("prompt_text")||""));e.set("prompt_text",b);return e}catch(c){}return null}Li(a,{content:b,
entrypoint:c}){if(!a.FP.signal.aborted&&a===g3D(this)){var d=!1;c&&c!==a.entrypoint&&(d=!0,a.entrypoint=c,a.entrypointId=_.w_h(c),L2D(a));J2D(a.content,b)||(d=!0,a.content=b);d&&a.RNa&&t3D(this,{replace:!0})}}async F_b(a){this.oa.at(-1);a.RNa||(a.RNa=t3D(this,{replace:!!a.ZPe}))}onDismiss(a){return({yK:b,eventType:c})=>{if(!this.oa.includes(a))return a.yK.resolve(b),!0;if(a!==g3D(this))return!1;a.yK.resolve(b);a:switch(c){case 2:b=3;break a;case 0:b=4;break a;default:b=0}i3D(this,a,b).catch(()=>{});
B3D(this,a);return!0}}};_.fg(_.Z3a,_.C3D);

_.x();
});
// Google Inc.
